### ISSUE TITLE
Adding table constraints 

### ISSUE THREAD

**Issue by ojundt** [ankane/strong_migrations#10]
Hi, I just ran across a scenario that might be interesting to add to this gem.

We are using Postgres and if you add a new constraint to an existing table it will lock the whole table with an exclusive lock. For example:

```SQL 
ALTER TABLE products ADD CONSTRAINT positive_price CHECK (price > 0);`
```

However, a much better approach is using the `NOT VALID` option. With that option it's possible to add a new constraint that only applies to new and updated records while temporarily skipping the expensive check for all existing rows. The existing rows can be checked using a separate `VALIDATE CONSTRAINT` command with a much less intrusive `SHARE UPDATE EXCLUSIVE` lock. For example:

```SQL
ALTER TABLE products ADD CONSTRAINT positive_price CHECK (price > 0) NOT VALID;
ALTER TABLE products VALIDATE CONSTRAINT positive_price;
```

Source: https://www.postgresql.org/docs/9.6/static/sql-altertable.html

I'm not sure if this scenario is a good fit for this gem, though, as there is no default Rails method for adding such constraints and thus intercepting it is much harder. Also it probably does not apply to all SQL database systems. What do you think?

**Comment by ankane** [comment]
Hey @ojundt, thanks for sharing. Happy to incorporate DBMS specific things into the gem (there are already some PostgreSQL-specific ones). Since there's no Rails method, it won't need a code change, but we could add a "Adding a constraint" section after "Adding a json column".

**Comment by Erowlin** [comment]
Do you plan to support that use case?
