### ISSUE TITLE
Suggestion for change_column_default 

### ISSUE THREAD

**Issue by gvpmahesh** [ankane/strong_migrations#117]
```
class AddSomeColumnToUsers < ActiveRecord::Migration[6.0]
  def up
    add_column :users, :some_column, :text
    change_column_default :users, :some_column, "default_value"
  end

  def down
    remove_column :users, :some_column
  end
end
```
This is the code that is suggested by the gem when we add default while adding the column. But however here is what happens

Let's say, I have a `User` model with 10 rows and columns are id, email. Now I am adding `metadata` column with the above syntax,  null/nil values will be present for the previous 10 records.  For any new record that is going to be created, that will have default value. But the older records have the nil/null.

It should be like this

```
    add_column :users, :some_column, :text
    change_column_default :users, :some_column, "default_value"
    User.update_all(some_column: "default_value") # or something equivalent
```
This would be helpful for people like who straightaway copies what the gem suggests :D

**Comment by ankane** [comment]
Hey @gvpmahesh, thanks for the suggestion. Both the readme and the error mention backfilling, so I'm not sure more is needed. Backfilling in the same transaction as a schema change is actually unsafe.
