### ISSUE TITLE
Easy way to ignore unsafe operations in pre-existing migrations

### ISSUE THREAD

**Issue by vergenzt** [ankane/strong_migrations#12]
My codebase has 164 migrations already, many of which include "unsafe" operations (likely created before the app was even in production).

Is there an easy way to "assure safety" for all migrations before a certain version number?

**Comment by vergenzt** [comment]
Ahh never mind, just saw #3; will close this and continue there.

**Comment by vergenzt** [comment]
Actually, I think I am going to keep this open.

> There's no need to mark past migrations as safe. Rails recommends you use rake `db:schema:load` when creating a database from scratch (for instance, for new developers). Also, you can use:
> 
> ```
> SAFETY_ASSURED=1 rake db:migrate
> ```
> 
> if needed for the initial migration (if you really don't want to use `db:schema:load`)

My problem: I'd like my CI builds to confirm that new migrations work correctly and use only safe operations. Possibilities I see:

 1. ❌  **`rake db:schema:load`**

    Doesn't run the migrations, so provides no guarantees that they work, nor even a way to confirm that they were run by the developer. (If it's not running `db:migrate` then there will never be a diff against `schema.rb` to fail with.)

 2. ❌  **`SAFETY_ASSURED=1 rake db:migrate`**

    Doesn't check any safety guarantees.

 3. ⚠️  **`rake db:migrate`**

    Works, but requires me to update all prior migrations to add `safety_assured { ... }`, which is a PITA.

If I could configure a version number before which all migrations should be considered "safe", option (3) would be perfect.

**Comment by ankane** [comment]
Hey @vergenzt, I'm not sure what testing safe migrations gets you, but you can always go back and add safety_assured if you don't want to use db:schema:load for tests.

**Comment by vergenzt** [comment]
> I'm not sure what testing safe migrations gets you

Makes sure the build fails if we try to introduce an unsafe migration? Not absolutely required, but it would be nice to be warned by the CI system if we unwittingly introduce a migration that's going to balk in production.

> ... but you can always go back and add safety_assured if you don't want to use db:schema:load for tests.

We have 163 pre-existing migrations though, and it'd be a major pain in the butt to go back and mark each of them as safe, especially since there's not an obvious way to do that automatically e.g. with `sed` magic.

I completely understand if you don't want to write this since you don't have a use case for it, but would you be open to accepting a PR? It'd clearly be useful to a good handful of people.
