### ISSUE TITLE
rails generate strong_migrations:install is not found

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/strong_migrations#121]
Hey ankane,

Quick Question regards to installtion and test:db:prepare

- I do see rails generate strong_migrations: install doesn't work for me, is there a specific rails version I need to be in for this to be working 

Current rails version is `5.1.7`

- I don't see strong migrations checks run when i run test:db:preapre but does work for rake db:migrate is there a configuration I should do for test:db:preapare also picks these checks 

Thanks 
Bheem

**Comment by ankane** [comment]
Hey @bheemreddy181,

1. Make sure you're on the latest version of Strong Migrations for the generator.
2. `test:db:prepare` loads the schema directly rather than calling `db:migrate`, and checks are always disabled for schema loading since it would fail if they were enabled.

**Comment by bheemreddy181** [comment]
Cool thanks , is there a way we can emit logs for timeouts for each migrations something like this

 ```
== 20190525011402 ReactivateTestPaymentScheduleOnContract: migrating ==========
-- set_setting(:lock_timeout, 500)
-- set_setting(:statement_timeout, 1500)
-- set_setting(:statement_timeout, 0)
-- set_setting(:lock_timeout, 0)
== 20190525011402 ReactivateTestPaymentScheduleOnContract: migrated (0.4250s) =
```

**Comment by ankane** [comment]
You should be able to see the statements if you enable Active Record logging. I think it'll be overly noisy to add them to the normal output, but will consider an option if there's significant demand.

**Comment by bheemreddy181** [comment]
Sounds good thanks
