### ISSUE TITLE
Making an existing column NOT NULL in PG 12+

### ISSUE THREAD

**Issue by jjb** [ankane/strong_migrations#122]
There's a hidden gem in PG 12 that allows making an existing column NOT NULL without a table scan.

I have a recipe here: https://gist.github.com/jjb/fab5cc5f0e1b23af28694db4fc01c55a

There are links to explanation/discussion at the bottom.

This might be worth mentioning in the readme?

**Comment by ankane** [comment]
Hey @jjb, this should actually be in the latest release. https://github.com/ankane/strong_migrations#setting-not-null-on-an-existing-column

**Comment by jjb** [comment]
Whoops! I actually glanced over that but didn't realize it was the same concept. I made a PR to maybe improve the docs. Feel free to reject/reword.
