### ISSUE TITLE
Idea: add "how it works"

### ISSUE THREAD

**Issue by axlekb** [ankane/strong_migrations#124]
Hello!

Long time `rails` user, and someone just now got recommended this gem.  Looks like a lot of great features, thank you!  Just wanted to let you know that as I read the README what was missing for me was "how it actually works", or "how to trigger the checks" and "what happens if a check fails".  Maybe that's what was intended by "Prevents them from running" in the top level feature list, but for me it would have been useful to have something like the following in the README after the Installation section:

> Now when you run a migration that is deemed unsafe you'll see an error message:
> ```
> $ rake db:migrate
> Migrating to AddBadMigration (20200603155750)
> == 20200603155750 AddBadMigration: migrating ==============================
> rake aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> === Dangerous operation detected #strong_migrations ===
>   <details about the error>
>  ```

**Comment by ankane** [comment]
Hey @axlekb, thanks for the suggestion. Added here: https://github.com/ankane/strong_migrations#how-it-works
