### ISSUE TITLE
[Idea] Support for `rein` gem?

### ISSUE THREAD

**Issue by mockdeep** [ankane/strong_migrations#126]
We're using [rein](https://github.com/nullobject/rein) for check constraints to prevent many of the issues reported by `strong_migrations`, but we still need to wrap them in `safety_assured` blocks. It would be nice if `strong_migrations` understood the utilities from `rein` enough to not report issues when we're using it correctly.

**Comment by ankane** [comment]
Hey @mockdeep, thanks for the suggestion! I don't think it's something I'd like to support right now, but I believe you could create an initializer (or gem) to handle it:

```ruby
module ReinSafety
  def add_null_constraint(*args, **options)
    if options[:validate] == false
      safety_assured { super } 
    else
      super
    end
  end
end

ActiveRecord::Migration.prepend(ReinSafety)
```
