### ISSUE TITLE
Increasing varchar length in postgres should be safe

### ISSUE THREAD

**Issue by reedstonefood** [ankane/strong_migrations#128]
In [this commit](https://github.com/ankane/strong_migrations/commit/a8b0e37af46cc00e00e022dfa4f89dcbff0d8fca), a change was made which made this a safe operation:

> Changing a `varchar` column to `text`

It also made changing `decimal` and `numeric` columns to have a higher precision or be unconstrained a safe operation too.

However, looking at the [changelog for 9.2](https://www.postgresql.org/docs/release/9.2.0/), it says:

> Increasing the length limit for a varchar or varbit column, or removing the limit altogether, no longer requires a table rewrite. Similarly, increasing the allowable precision of a numeric column, or changing a column from constrained numeric to unconstrained numeric, no longer requires a table rewrite. 

So, as per that comment I think changing from (for example) `varchar(255)` to `varchar(500)` should also be a safe operation. Currently it is flagged as unsafe.

I'm happy to have a go at a PR for this, if it's agreed this is an issue.

**Comment by ankane** [comment]
Hey @reedstonefood, that operation should currently be safe. Are you seeing an error with a specific migration?

**Comment by reedstonefood** [comment]
Thanks the super-fast response @ankane . If I write a migration like this against a column that is currently `varchar(255)`...

```
class MakeStringLonger < ActiveRecord::Migration[6.0]
  def up
    change_column :some_table, :some_column, :string, limit: 500
  end

  def down
    change_column :some_table, :some_column, :string, limit: 255
  end
end
```

When I run `rake db:migrate` I get:

```
== 20200708125405 MakeStringLonger: migrating =================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

=== Dangerous operation detected #strong_migrations ===

Changing the type of an existing column requires the entire
table and indexes to be rewritten. A safer approach is to:
...
...
```

This is in postgres 11.6.

**Comment by ankane** [comment]
Hmm, there's a test for a similar migration here: https://github.com/ankane/strong_migrations/blob/7609c9d122f0f8b75f4b47f27ddef0d65ef62702/test/migrations.rb#L112-L120

I'd double check your app is configured to use Postgres. If so and it's still an issue, feel free to submit a PR.

**Comment by reedstonefood** [comment]
OK, it's because we're not on the latest version 🤦 

I would however suggest the documentation here could be updated to show this type of migration is considered safe.

**Comment by ankane** [comment]
Added to docs
