### ISSUE TITLE
Question : How do we verify whether the timeouts are set correctly ?

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/strong_migrations#133]
We recently had a timeout issue in production 

we have these value in my /strong_migration.rb file 

```
StrongMigrations.statement_timeout = 3000
StrongMigrations.lock_timeout = 500
```

but it took way longer than 500 milliseconds 

strong_migrations version 0.6.4, Can we emit out logs which will explain the timeouts are set correctly ?

**Comment by ankane** [comment]
Timeouts are in seconds, and the latest version warns if the lock timeout is greater than 10 seconds.

You can check timeouts in a migration with:

```ruby
p connection.select_all("SHOW lock_timeout").to_a
p connection.select_all("SHOW statement_timeout").to_a
```

(the above is for Postgres - change the statements as needed for MySQL)

**Comment by bheemreddy181** [comment]
Thanks - Do we want to emit out explicit logs for these timeouts - similar to active record logs for migrations >

**Comment by ankane** [comment]
Also, float timeouts (like `0.5.seconds`) aren't currently supported, but I just pushed code to add it.

I think it'll be noisy to log, but feel free to add logging to your application.

**Comment by bheemreddy181** [comment]
logs I feel are less noisy and more informational, we don't run migrations on every prod release - I feel the logs are useful , do these timeouts work even with pgbouncer in place?

**Comment by bheemreddy181** [comment]
What is a transaction_mode in pgbouncer i could see this in the documentation

`Note: If you use PgBouncer in transaction mode, you must set timeouts on the database user.`

**Comment by bheemreddy181** [comment]
I got the answers for above from my DBA's , when can I expect a new release?

**Comment by bheemreddy181** [comment]
Thanks for the new release @ankane  Appreciate all your work here :-)

**Comment by delphaber** [comment]
> Timeouts are in seconds, and the latest version warns if the lock timeout is greater than 10 seconds.

@ankane why is 10 seconds some sort of soft limit? Is it really strange to set it higher? Just wondering :)

**Comment by ankane** [comment]
@delphaber this is essentially how long you can tolerate reads or writes being blocked on a table, so 5-10 seconds seems reasonable for many applications.
