### ISSUE TITLE
timeouts with remove_column

### ISSUE THREAD

**Issue by mockdeep** [ankane/strong_migrations#135]
We've noticed a couple of times when we've been trying to drop a column that it has taken a surprisingly long time. It has reached our statement timeout of 10 seconds, which prevented any user facing issues. After a retry or two it finally went through. Everything I see around the web seems to say that it should be fast, but no such luck for us. I don't see any concurrency options anywhere for it, so I'm not sure there's anything `strong_migrations` can suggest, but thought I'd put it out there.

The column in question is relatively simple without any cascading dependencies:

```rb
t.json "saved_signature", default: {}, null: false
```

Is there any reason the `default` or `null: false` would cause the migration to slow down? Do we need to remove those separately?

**Comment by ankane** [comment]
Hey @mockdeep, it's probably having trouble getting a lock on the table. If you set the lock timeout to be lower than the statement timeout, you can see if a lock timeout occurs. If that's the case, a few things you can try are:

- For high traffic tables, run migrations at a lower traffic time 
- Poll the database for locks / blocked queries while it's running to see what's causing it

**Comment by mockdeep** [comment]
@ankane yeah, this is the lock timeout that is firing. Our timeouts are the [same as in your docs](https://github.com/ankane/strong_migrations#migration-timeouts). I'm not really sure what would be better, but everybody goes into high alert every time something like this happens on a deploy. Anyway, feel free to close if you don't think there's anything to be done here.

**Comment by ankane** [comment]
Strong Migrations may have the option to retry lock timeouts automatically at some point. You can lower the lock timeout for more safety (and more timeouts), but what you're seeing is expected at scale (at least in my experience).

**Comment by ankane** [comment]
I also made a note to look into friendlier error messages for timeouts in #95. Maybe something like "Don't worry, this typically happens when the table is busy. If it still times out after a few tries, try again at a lower traffic time."
