### ISSUE TITLE
Removing NOT NULL constraint doesn't raise warning

### ISSUE THREAD

**Issue by Brentwish** [ankane/strong_migrations#136]
Hi,

Opening this issue because I suspect strong_migrations should have warned against the following migration.
```
class RemoveSomeColumnNotNullSomeModel < ActiveRecord::Migration[5.2]
  def change
    change_column_null :some_model, :some_column, true
  end
end
```

This migrations generates:
```
[28] pry(main)> ActiveRecord::Migration[5.2].change_column_null(:some_model, :some_column, true)
-- change_column_null(:some_model, :some_column, true)
   ALTER TABLE "some_model" ALTER COLUMN "some_column" DROP NOT NULL
```

This held an exclusive lock on the table which ended up bringing us down for a few minutes. 😿 

Should strong migrations have warned against this migration?

Thanks!

**Comment by ankane** [comment]
Hey @Brentwish, that should be a fast operation once a lock is acquired. My guess is you're missing a lock timeout (recent versions of Strong Migrations should warn about this).

Here's a short example you can run in `psql` to confirm it's fast (requires 7GB of space)

```sql
\timing
CREATE TABLE t1 (id bigserial PRIMARY KEY, value text);
INSERT INTO t1 (id, value) SELECT i, 'test' || i FROM generate_series(1, 100000000) i;
ALTER TABLE t1 ALTER COLUMN value SET NOT NULL;  -- 12,000 ms (slow)
ALTER TABLE t1 ALTER COLUMN value DROP NOT NULL; -- 3 ms (fast)
```

**Comment by Brentwish** [comment]
Thanks for posting!

I ran your example and it's definitely a fast operation for that table (mine ran in 2100ms though). Though the migration ran for 5 minutes before manually killing it. We're considering disabling advisory locks altogether.

**Comment by ankane** [comment]
Advisory locks don't block operations, so I don't think that was the cause. Here's how to set the lock timeout for migrations: https://github.com/ankane/strong_migrations#migration-timeouts. Going to close since it shouldn't be a dangerous operation when a lock timeout is set.
