### ISSUE TITLE
Catch `.each` on relations

### ISSUE THREAD

**Issue by fatkodima** [ankane/strong_migrations#138]
I made such mistakes several times, so would be great to catch those.

In migration file, i wrote:
```ruby
...
def up
  ...
  User.each do |user|
    user.update(...)
  end
end
...
```

instead of:
```ruby
...
def up
  ...
  User.find_each do |user|
    user.update(...)
  end
end
...
```

accidentally loading several millions of users into memory and failing the migration.
Also, would be great, i think, to warn about `.update_all` (maybe other methods too), as this potentially can lock the table while updating.

I can submit a pr, if this seems reasonable.

**Comment by ankane** [comment]
Hey @fatkodima, thanks for the suggestion. At this point, I don't want to expand the scope to Active Record calls, but let me know if you decide to fork and add it (or create a separate gem for it).

**Comment by fatkodima** [comment]
Not interested in a separate gem at this point. Feel free to close this. 😉
