### ISSUE TITLE
Change column null quoting

### ISSUE THREAD

**Issue by excid3** [ankane/strong_migrations#139]
Hey Andrew! Was just using this today to set a couple columns as `null: false` and ran into an issue, then found an outstanding TODO that mentioned the situation:

```
# TODO likely need to quote the column in some situations
safe = constraints(table).any? { |c| c["def"] == "CHECK ((#{column} IS NOT NULL))" }
```

I have a column called `interval` and that seems to be quoted, but my other `name` columns I was doing were not.

```
irb(#<StrongMigrations::Checker:0x00007fe3cac5a610>):001:0> column
=> :interval
irb(#<StrongMigrations::Checker:0x00007fe3cac5a610>):003:0> constraints(table)
=> [{"name"=>"plans_name_null", "def"=>"CHECK ((name IS NOT NULL))"}, {"name"=>"plans_interval_null", "def"=>"CHECK ((\"interval\" IS NOT NULL))"}]
```

I presume this is because of the `interval` date/time feature in Postgres.

I don't know if there's a way to detect if it's a reserved word, but a simple solution would be to search for strings with and without quotes. Thoughts on that approach?

**Comment by ankane** [comment]
Hey Chris, thanks for reporting! That approach makes sense to me. Can you give master a shot?

**Comment by excid3** [comment]
Works perfectly. Thanks @ankane 👍
