### ISSUE TITLE
Rails 5 in_batches method

### ISSUE THREAD

**Issue by vlymar** [ankane/strong_migrations#14]
First off, thanks a ton for this fantastic guide.

I was recently following the instructions for [adding a column](https://github.com/ankane/strong_migrations#adding-a-column-with-a-default-value) and wondered if there was a cleaner way to batch update yet.

Turns out in rails 5 there's a new [in_batches](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-in_batches) method that can yield enumerators of relation objects, which lets you rewrite 

```ruby
User.find_in_batches do |users|
  User.where(id: users.map(&:id)).update_all some_column: "default_value"
end
```

as 

```ruby
User.in_batches.update_all some_column: "default_value"
```

If you also prefer the aesthetics of this new method, I can go ahead and open a PR with that option for Rails 5. But if you don't want to clutter the guide with more "For Rails < 5 use this, for Rails >= 5 use that", I understand. Just thought I'd share this new method :)

**Comment by ankane** [comment]
Hey @vlymar, thanks for sharing. It's definitely has a cleaner look. I'm happy to accept a PR to replace the current suggestion.
