### ISSUE TITLE
There's no strong_migrations generator at all

### ISSUE THREAD

**Issue by sevenmaxis** [ankane/strong_migrations#140]
Hi,

I've installed the `string_migrations` into RoR 4.2 project.
And then run `bundle exec rails generate strong_migrations:install` command and got error:

`Could not find generator 'strong_migrations:install'...`

`bin/spring stop` didn't help, `rails generator` doesn't list the `strong_migrations` generator.

**Comment by ankane** [comment]
Hey @sevenmaxis, v0.3.1 was the last version to support Rails 4.2, so you'll want to use the readme for that version (or whichever version you have installed). https://github.com/ankane/strong_migrations/tree/v0.3.1
