### ISSUE TITLE
[Idea] Support for nulldb adapter. Interested in PR?

### ISSUE THREAD

**Issue by dhnaranjo** [ankane/strong_migrations#142]
What's good?

So, we started using `strong_migrations` because I kept hanging deploys because I'm a fraud. You know how it is. Anyways, it's great.

We're working on setting up a dockerized dev and deployment setup and we encountered an annoying need for our database to be available during Rails asset precompilation. Following the recommendation of [this here GH comment](https://github.com/globalize/globalize/issues/723#issuecomment-599705847) we adopted https://github.com/nulldb/nulldb, which just makes a "functional" database that doesn't do nothin. This worked great, then we shelved the effort for a bit, after which we added `strong_migrations`. Now it doesn't work.

Specific error, though I suspect we'll encounter more issues if we get deeper in the chain:
![image](https://user-images.githubusercontent.com/536280/110150769-407de380-7da5-11eb-8f5b-abffb2342062.png)

What I'm proposing is either:
- Make `strong_migrations` aware of the `nulldb` adapter and just not do anything
- Make `strong_migrations` able to skip all behavior if an env var is provided

I'd be happy to do the work, curious if you'd be interested in merging this in?

Thanks.

P.S. You're probably the 5th most productive engineer on my team. Gosh you write a lot of helpful stuff.

**Comment by dhnaranjo** [comment]
A quick hack of commenting out `set_timeouts` and `check_lock_timeout` in `lib/strong_migrations/checker.rb#perform` allows the process to complete successfully.

**Comment by ankane** [comment]
Hey @dhnaranjo, thanks for the suggestion, and glad to be part of the team :) Timeouts shouldn't be needed on schema load, so I've disabled them in the commit above. I think that should fix any `nulldb` issues, but let me know if not.

**Comment by dhnaranjo** [comment]
That absolutely resolved the issue. Thanks so much.
