### ISSUE TITLE
More fine-tuned checks

### ISSUE THREAD

**Issue by pjmartorell** [ankane/strong_migrations#145]
Hi, I'm trying to upgrade to a newer version to get rid of Ruby 2.7 deprecation warnings, but when trying to upgrade to version `0.6.4` I noticed that in this version there is a new condition in the `add_reference` check that raises `Adding a validated foreign key locks the table. Then add the foreign key in separate migrations` when adding a foreign key to a column with an index:
https://github.com/ankane/strong_migrations/blob/46bc658fe3f923a23a1ad14d82653d153ba90ae9/lib/strong_migrations/checker.rb#L176-L183

This new condition is making many old migrations to fail and rewriting all of them is unfeasible for me right now. I tried to circumvent the issue disabling the check with `StrongMigrations.disable_check(:add_reference)` or enabling the check from a specific version with `StrongMigrations.enable_check(:add_reference, start_after: 2021_03_12_155302)` but this makes the foreign keys **not to be added**, in example:
```
  disable_ddl_transaction!

  def up
    add_reference :table1, :table2, index: { algorithm: :concurrently }, foreign_key: true
  end
```

The problem is that `add_reference` check now is being used for more than one check. Could it be possible to create more fine-tuned checks so it's possible to enable the `concurrently` check but not the `foreign_key` check? 

I think in general it would be better not to change the behaviour of checks, but to add more specific checks to the existing ones so they can be enabled/disabled more granularly. Otherwise it makes upgrading to newer versions much more difficult because many old migrations start failing.

**Comment by ankane** [comment]
Hey @pjmartorell, I wasn't able to reproduce the behavior of `disable_check` and `enable_check(..., start_after: ...)` causing foreign keys not to be added.

I think it makes sense to have the checks combined here to prevent Strong Migrations from making suggestions that can cause downtime. In either case, users that want to disable the check before a certain time will need to use `enable_check(..., start_after: ...)`.
