### ISSUE TITLE
[Idea] Require `type` option on `reference`/`belongs_to` columns when `primary_key_type` is set

### ISSUE THREAD

**Issue by kayla-glick** [ankane/strong_migrations#147]
## Context
Rails provides a generator config option `primary_key_type` to set a default primary key type when it generates migrations.
```
Rails.application.config.generators do |g|
  # one option
  g.orm :active_record, primary_key_type: :uuid
  # another example
  g.orm :active_record, primary_key_type: "uuid, default: -> { 'uuid_generate_v4()' }"
end
```
This automatically adds `id: :uuid` to `create_table` statements. It does not however affect `reference` statements.

## Problem
Say we have two models, `Foo` and `Bar`
```
class Foo < ApplicationRecord
  has_many :bars, dependent: :destroy
end

class Bar < ApplicationRecord
  belongs_to :foo 
end
```

and we use the Rails generator to create tables for them with `primary_key_type` `:uuid`
```
rails g migration create_foos
rails g migration create_bars
```

```
class CreateFoos < ActiveRecord::Migration[6.0]
  def change
    create_table :foos, id: :uuid do |t|
    end
  end
end

class CreateBars < ActiveRecord::Migration[6.0]
  def change
    create_table :bars, id: :uuid do |t|
    end
  end
end
```

Then we add the reference for the `belongs_to` association
```
create_table :bars, id: :uuid, default: -> { 'uuid_generate_v4()' } do |t|
  t.references :foo, null: false, foreign_key: true # Dev assumes this will be type: :uuid by default
end
```

This migration will run just fine, but there's actually a massive problem. `foos.id` is a `uuid` type, but `bars.foo_id` is now a `bigint` and the real `foo_id` won't be saved properly. 
It seems that developers are expected to know to add `type: :uuid` on the reference column, but in practice this seems to be a common mistake. [This Rails issue](https://github.com/rails/rails/issues/23422) has 5 years of comments complaining about this functionality, and I also wanted to open this issue because we've been running into it at my company.
I don't believe that any of the solutions proposed in that thread adequately address the issue. One suggestion would help if adding the column via the `rails g migration` command, but it doesn't help if you add the columns by hand. Others have suggested that the the migration should look up the corresponding primary key in the database, but per @matthewd on the Rails team, migrations should not inspect the current state of the database to infer the type of the reference column. 

After reading the discussion on the Rails core issue I thought that this might be a good feature for `strong_migrations` instead.

## Proposal
When `Rails.application.config.generators.active_record[:primary_key_type]` is set and a developer tries to run a migration with a `reference/belongs_to` column without a specified `type`, `strong_migrations` should warn them that they may need to add the `type` option to match the primary key's type. This should maybe be over-writable within a migration since there could be a case where some tables are using a different primary key type.

Using the above example, when I run `rake db:migrate`, I would hope to see something like:
```
Warning: Please specify a type on your reference columns to match the corresponding Primary Key
<migration_file_name>:line_number in t.references ...
```

**Comment by ankane** [comment]
Hey @kayla-glick, thanks for the suggestion (and great explanation)! I think it's a bit outside the scope of the gem, but you should be able to use [custom checks](https://github.com/ankane/strong_migrations#custom-checks) for it (either to warn or raise an error). Users can then use `safety_assured` to override the check when needed. Please share if you do.

**Comment by kayla-glick** [comment]
Thanks @ankane! I'll try that! If it works well I'll make a suggestion on the Rails thread about this issue too.

**Comment by kayla-glick** [comment]
Is there a way to view the columns being added inside a `create_table` statement to be able to see if a reference is being added like in the example for the `create_bars` migration? 

```
StrongMigrations.add_check do |method, args|
  puts method # :create_table
  puts args # [:bars, {:id=>:uuid, :default=>#<Proc:0x00007f8d5cf5bb80@/<redacted>/db/migrate/20210506143336_create_bars.rb:3 (lambda)>}]
end
