### ISSUE TITLE
[Idea] Collect tables to ANALYZE to run at end of migrations

### ISSUE THREAD

**Issue by hmcfletch** [ankane/strong_migrations#150]
I recently ran into an issues where I was adding a number of partial indexes to a large table in the same migration. Since we had `StrongMigrations.auto_analyze` turned on an `ANALYZE` was run after each `add_index`. I turned off `auto_analyze` and added some code to our own app to collect all of the tables that had indexes added to run a single `ANALYZE` at the end of the migration for each of these tables. I additionally collected the columns being indexes for each table to only `ANALYZE` those columns to speed things up a bit as well.

Any thoughts on this approach?

**Comment by ankane** [comment]
Hey @hmcfletch, thanks for the suggestion. I think it's better to run `ANALYZE` immediately after an index is created to minimize the time that out-of-date statistics are used. I also think it's good to update statistics for all columns on the table since they may be used in query planning (and it shouldn't take much more time).

**Comment by hmcfletch** [comment]
First, thanks for responding and for all of the great gems!

I agree with updating all columns. I did some tests and didn't find enough of a difference to warrant only updating a few columns.

Would running `ANALYZE` before adding the index work? Does the index need to be present when `ANALYZE` is run? If not, there could be a (optional) check for adding multiple indexes to the same table in the same migration. To run the `ANALYZE` before adding all of the indexes could be done by doing something like:

```ruby
analyze_before_indexes :table do
  add_index :table, :col1
  add_index :table, :col2
end
```

Of course, this is only if running `ANALYZE` before the adding the indexes works.

**Comment by ankane** [comment]
I'm not sure if there's any difference running it before or after (have always run it after), but not sure extra complexity is needed. `ANALYZE` should be fairly quick, and users can update `StrongMigrations.auto_analyze` if they need to.

**Comment by hmcfletch** [comment]
If you have hundreds of millions of rows and increased the statistics target to the max `ANALYZE` can take a while to run. For the table I'm working with it takes between 25-40 minutes to run, hence only wanting to run it once.

**Comment by ankane** [comment]
Thanks for the additional context. I think it's best to fork if updating `StrongMigrations.auto_analyze` doesn't work for your use case.
