### ISSUE TITLE
The `faster migrations` section does not work with spring

### ISSUE THREAD

**Issue by scottjacobsen** [ankane/strong_migrations#152]
The code in the [Faster Migrations](https://github.com/ankane/strong_migrations#faster-migrations) section does not work with spring, because it only executes once when spring starts up. If a migration is created after that the schema dumper does not run because the `dump_schema_after_migration` value remains `false` in the process forked off the main spring process (the initializers do not re-run).

To solve this I used `prepend` to override  the `dump_schema_after_migration` accessor to run the `git` command each time it is called. I added this to an initializer. I call `super` first  - on the off chance a user sets the `dump_schema_after_migration` configuration to `false` in development mode that configuration will continue to be honored even if there is a change in the migration directory.

```ruby
module MySmartSchemaDumper
  def dump_schema_after_migration
    super && `git status db/migrate/ --porcelain`.present?
  end
end

if Rails.env.development?
  ActiveRecord::Base.class_eval do
    class << self
      prepend MySmartSchemaDumper
    end
  end
end

**Comment by ankane** [comment]
Hey @scottjacobsen, thanks for reporting! Updated the instructions in the commit above.

**Comment by ankane** [comment]
fwiw, Spring seems to reload the initializer in the Rails versions I tried (5.2 and 6.1). I think the new pattern is better (since it only executes the code for migrations), but what versions were you seeing this behavior with?
