### ISSUE TITLE
Enable remove_index check by default

### ISSUE THREAD

**Issue by jscheid** [ankane/strong_migrations#153]
I'd like to suggest enabling the `remove_index` check by default.

The docs [say](https://github.com/ankane/strong_migrations/tree/afa553ad3738e025e385d286daea12b894eaff17#removing-an-index-non-concurrently) that "removing [an index] non-concurrently shouldn’t be an issue for most applications" which is true, but does it take into account the fact that rolling back a migration containing a non-concurrent `remove_index` will cause the index to be added non-concurrently?

**Comment by ankane** [comment]
Hey @jscheid, thanks for the suggestion, but want to keep it opt-in. Down migrations aren't check by default, but there's an option for it as well.
