### ISSUE TITLE
[Idea] Check before running creating a unique index on PSQL

### ISSUE THREAD

**Issue by kopylovvlad** [ankane/strong_migrations#154]
Hi! Thank you for the awesome gem.

I have one question about [adding an index non-concurrently](https://github.com/ankane/strong_migrations#adding-an-index-non-concurrently). According to [PSQL documentation](https://www.postgresql.org/docs/9.1/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY) creating unique index can be dangerous.

> If a problem arises while scanning the table, such as a uniqueness violation in a unique index, the CREATE INDEX command will fail but leave behind an "invalid" index. This index will be ignored for querying purposes because it might be incomplete; however it will still consume update overhead.

For instance, I have one table 'users' and I'm going to add a uniq index on email field

```ruby
class AddIndexToFakeName < ActiveRecord::Migration[5.0]
  disable_ddl_transaction!

  def change
    add_index :users, :email, unique: true, algorithm: :concurrently
  end
end
```

If there are any duplicates in the table, during running the migration it will fail with the error:

> Caused by:
> ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
> DETAIL:  Key (email)=(mail@mail.com) is duplicated.
> : CREATE UNIQUE INDEX CONCURRENTLY "index_users_on_email" ON "users"  ("email")
> 

In the database, the index will exist and it's invalid.

> $ \d users
> 
> Indexes:
>     "index_users_on_email" UNIQUE, btree (email) INVALID

After the incident, if I run the migration again it will fail with another error because the index has already existed.

> Caused by:
> ArgumentError: Index name 'index_users_on_email' on table 'users' already exists
> 

Really awkward situation. The way to fix is to delete the index manually and after that find and fix duplicates in the table

## Solutions: 

To add any check before running creating a unique index. I don't know the best way for data verification before running creating the index. But it's necessary to check that we don't have any duplicates in the table.

It will be better if the gem will warn about the behaviour and suggest any solution.

Version: strong_migrations (0.7.7)

**Comment by ankane** [comment]
Hey @kopylovvlad, thanks for the suggestion, but think it's best for the database to try and create the index. Deleting the invalid index and re-running the migration shouldn't be an issue.

**Comment by kopylovvlad** [comment]
Ok, it makes sense. The migration should know nothing about the database.

According to `README.md` adding an index non-concurrently is a Postgres-specific check. 
The gem has already known information the database. Maybe the gem should warn us about the behaviour of Postgres? 🤔 

For instance to improve the message [here](https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations.rb#L127). If a developer tries to create an index with `unique: true` params, the gem could print out the message:

```
Creating a unique index non-concurrently would cause errors and affect your database. A safer approach is to:

1. Check there are no duplicates in the column of the table <table name>
2. Check the table hasn't already had invalid index via `\d <table name>`
3. Run the migration
```

What do you think about it?

**Comment by ankane** [comment]
If there are duplicates or an existing invalid index, the migration will raise an error, so I don't think there's a need to do 1 or 2 before running the migration.
