### ISSUE TITLE
add_reference produces wrong sql statement when safe_by_default is true

### ISSUE THREAD

**Issue by aantoniadis** [ankane/strong_migrations#155]
It seems that strong_migrations library produces SQL statement for `add_reference` (with the option `foreign_key: { to_table: :table }`) does not take into account the `ref_name` parameter if we set `StrongMigrations.safe_by_default = true`
As a result, such migrations fail with an error like the following:
```
PG::UndefinedColumn: ERROR:  column "XXXX_id" referenced in foreign key constraint does not exist
```

Steps to reproduce the issue:
```ruby
class AddAuthorToPosts < ActiveRecord::Migration[5.2]
  def change
    add_reference :posts, :author, foreign_key: { to_table: :users }
  end
end
```

Expected SQL statement:
```sql
ALTER TABLE "posts" ADD CONSTRAINT "fk_rails_XXXX"
FOREIGN KEY ("author_id")
  REFERENCES "users" ("id")
```

Actual SQL statement
```sql
ALTER TABLE "posts" ADD CONSTRAINT "fk_rails_XXXX"
FOREIGN KEY ("user_id")
  REFERENCES "users" ("id")
```
Notice that the foreign key is user_id instead of author_id.

Also, if we rerun the migration, we get a different error
```
PG::DuplicateColumn: ERROR:  column "author_id" of relation "posts" already exists.
```
I guess that this is caused because the transaction is disabled, so the column for the FK is being created, but the add_foreign_key fails later because it doesn't take into account the reference name.

A quick (and dirty) solution that I tried, and seems to work, is to add the following in the [SafeMethods#safe_add_reference](https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations/safe_methods.rb#L33) method, but I guess it might not be that simple:

```ruby
if reference
  @migration.add_foreign_key(table, name, column: "#{reference}_id")
else
  @migration.add_foreign_key(table, name)
end
```

**Comment by ankane** [comment]
Hey @aantoniadis, thanks for the great report and fix!
