### ISSUE TITLE
[Idea] Including dropping a table as dangerous

### ISSUE THREAD

**Issue by ThHareau** [ankane/strong_migrations#156]
Hi,
We had an issue a couple of days ago due to dropping a table and its usage in the same rollout. What happened is that first the migration was executed, then the code was updated. So for a few minutes (we have a heavy DB), we got plenty of errors.

I see that this was considered in #49 and #53. I understand why these issues were closed, but I would still like to challenge this.

To give a few reasons why it would be good to have `drop_table` included in the dangerous operations: 
* I find this failure surprising. Indeed, even if you clean your code in the same commit, it can cause issue because it will be effective only once all the instance of the application are updated
* The consequence can be high if another migration is locked for a while after the deletion of the table; the issue can be here for a long time

**Comment by ankane** [comment]
Hey @ThHareau, I still have the same thoughts as the previous issues, but you can add a custom check for it to your application.

**Comment by ThHareau** [comment]
Ok :)
