### ISSUE TITLE
[Idea] Renaming a table with a temporary view when using Postgres

### ISSUE THREAD

**Issue by pirj** [ankane/strong_migrations#160]
The [currently suggested approach to rename a table](https://github.com/ankane/strong_migrations#renaming-a-table) is quite complicated:

- Deployment 1:
   - Create a new table
   - Write to both tables
   - Backfill data from the old table to new table
- Deployment 2:
   - Move reads from the old table to the new table
- Deployment 3:
   - Stop writing to the old table
   - Drop the old table

What do you think of a different approach:
- Deployment 1:
   - Create a view with the new name
   - Start reading and writing to the new "table"
- Deployment 2:
   - Drop the view
   - Rename the table

or even:
- Deployment 1:
   - Rename the table
   - Create a view for the old name
   - Start reading and writing to the new table
- Deployment 2:
   - Drop the view with the old name

This most probably won't work equally fine with MySQL/MariaDB (due to the [implicit commit for `RENAME TABLE`](https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html)).

https://www.postgresql.org/docs/9.3/sql-createview.html:
> Simple views are automatically updatable: the system will allow `INSERT`, `UPDATE` and `DELETE` statements to be used on the view in the same way as on a regular table.

On a side note, this could probably be used for renaming columns **along** with the table rename. Old table would accept reads/writes for old column name, the new table - for old names. To qualify as a simple view, column names don't have to have the same names:
> All columns in the view's select list must be simple references to columns of the underlying relation.

```sql
    # select * from users;
    (0 rows)
    # create view losers as select * from users;
    # insert into losers (full_name, email) values ('abc', 'abc@example.com');
    # create view losers2 as select *, full_name as name, email as email_address from users;
    # insert into losers2 (name, email_address) values ('cde', 'cde@example.com');
    # select * from users;
      id  | full_name |      email
    ------+-----------+-----------------
     4002 | abc       | abc@example.com
     4003 | cde       | cde@example.com
    (2 rows)
```

**Comment by pirj** [comment]
It turns out that renaming columns can be done without renaming the table.
The approach is the same:
1. rename the table
2. create a view with both the old and the new name
3. deploy the code that exclusively uses the new name
4. drop the view
5. rename the table and rename the column

Sanity check:
```
# CREATE TABLE aaa (foo integer, bar integer);
# INSERT INTO aaa (foo, bar) VALUES (3,4);
# select * from aaa;
 foo | bar
-----+-----
   3 |   4
(1 row)

# CREATE VIEW ccc AS
  SELECT foo, foo AS boo, bar, bar AS zar FROM aaa;

# INSERT INTO ccc (boo, zar) VALUES (5,6);
# SELECT * FROM ccc;
 foo | boo | bar | zar
-----+-----+-----+-----
   3 |   3 |   4 |   4
   5 |   5 |   6 |   6
(2 rows)
```

Am I missing something?

**Comment by pirj** [comment]
There is at least one additional deployment step needed for this approach to work. See [[1](https://github.com/doctolib/safe-pg-migrations/pull/54#discussion_r724405651), [2](https://github.com/doctolib/safe-pg-migrations/pull/54#issuecomment-939476427)].
The problem is that Active Record is unable to infer the primary key if a view backs the model.
The old code (say, scale up during the deployment) will start failing to `Model.find(id)` since `Model` has no PK defined in the schema for the view.

The additional preparation step is to explicitly specify `self.primary_key=` for models backed by the renamed table, and make sure it is deployed before running the schema migration.

**Comment by ankane** [comment]
Hey @pirj, thanks for the suggestion! I haven't tried the view approach, but it looks like it's what [GitLab uses](https://docs.gitlab.com/ee/development/database/rename_database_tables.html). One piece missing from above is the schema cache workaround for things like default values (which also takes care of the primary key issue).

I don't think I want to add the complexity to Strong Migrations, as I'd generally recommend not renaming tables or columns (and if you do, it should be infrequent).

**Comment by pirj** [comment]
I agree that the added complexity, especially in certain use cases, is an absolute overkill for this approach. To an extent that adding this as a normal process becomes irrelevant due to the number of exceptions and additional precautionary steps to take. We've realized that [when working on a helper for `safe-pg-migrations`](https://github.com/doctolib/safe-pg-migrations/pull/54#issuecomment-939476427).

Agree that even if the currently suggested approaches to renaming tables and columns is quite tedious, at least they are straightforward.

I'll close this until, hopefully at some point in the future, PostgreSQL makes it possible to fetch PK metadata from a view, and makes the suggested approach transparent on the application level.
