### ISSUE TITLE
[Question] Query Throttling 

### ISSUE THREAD

**Issue by a-ali** [ankane/strong_migrations#163]
Hello,

Thanks a lot for the great effort, this gem is one of my favorites.

I don't get why do we need to throttle [here](https://github.com/ankane/strong_migrations/tree/v0.7.8#good-2)

```ruby
class BackfillSomeColumn < ActiveRecord::Migration[6.1]
  disable_ddl_transaction!
  
  def up
    User.unscoped.in_batches do |relation|
      relation.update_all some_column: "default_value"
      sleep(0.01) # throttle <- ?
    end
  end
end
```
That's also mentioned at the [Rails API](https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-in_batches), but I can't get why.

Is it to run the migrations while the app is running and not populate the database server (_I'm using PostgreSQL_) with lots of queries in a short time window?
Is it related to the table-level locks?
Also, is there a specific strategy to pick the optimal sleep duration?

Thank you.

**Comment by ankane** [comment]
Hey @a-ali, it spreads load over time on the database server. You can set the sleep duration to the lowest value that doesn't cause database CPU usage to spike.

**Comment by a-ali** [comment]
Thank you
