### ISSUE TITLE
[Idea]: safety_assured without block

### ISSUE THREAD

**Issue by jasonkarns** [ankane/strong_migrations#164]
Anecdotally, it seems most common for migrations to wrap the entire `change` method body in `safety_assured` block.

For migrations such as these, it would be nice if one could do:

```rb
class Example < ActiveRecord::Migration[6.1]
  safety_assured!

  def change
    # things
  end
end
```

This would be a corollary to `disable_ddl_transaction!` as it applies to the entire migration and eliminates the need for a block.

**Comment by ankane** [comment]
Hey @jasonkarns, thanks for the suggestion! It's an interesting idea and I like the API, but I'm hesitant to add another way of marking operations as safe. Out of curiosity, what types of operations do you typically see that with?
