### ISSUE TITLE
Treat `exec_query` the same as `execute`

### ISSUE THREAD

**Issue by jdufresne** [ankane/strong_migrations#167]
When using `execute` in a migration, strong migrations emits a warning. Good.

If I change the method to `exec_query`, effectively I have the same migration, but no warning.

https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-exec_query

The docs recommend this method, so it seems natural that it will be used:

https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-execute

> Note: depending on your database connector, the result returned by this method may be manually memory managed. Consider using the exec_query wrapper instead.

**Comment by ankane** [comment]
Hey @jdufresne, thanks for the suggestion! It looks like it's possible with any of the `exec_*` methods, but I'm not sure they're typically used for schema changes like `execute` ([migration docs](https://guides.rubyonrails.org/v6.1/active_record_migrations.html)), so I'm hesitant to add. However, users who want this can use custom checks.

**Comment by jdufresne** [comment]
Thanks for the response @ankane.

My team uses `exec_query` because:

1. The note in the Rails doc link above recommends it.
2. It provides a more consistent return value than `execute`. Often our migrations must act on the the return and the total migration can't be done in single SQL query.

I'm hesitant to add a bunch of custom checks to our projects. One thing that is nice about strong migrations is that requires very little configuration.

If in the end you decide to close with no action, no problem.

**Comment by ankane** [comment]
Thanks for the additional context. Don't think I want to take any action right now.
