### ISSUE TITLE
Set column NULL default behavior results in irreversible migrations

### ISSUE THREAD

**Issue by yakschuss** [ankane/strong_migrations#168]
Hi! The default behavior for setting NOT NULL on an existing column results in an irreversible migration.
https://github.com/ankane/strong_migrations#setting-not-null-on-an-existing-column
The `change` method for the first step - 
```
class SetSomeColumnNotNull < ActiveRecord::Migration[6.1]
  def change
    add_check_constraint :users, "some_column IS NOT NULL", name: "users_some_column_null", validate: false
  end
end
```
results in a default `down` that is 
```
== 20220103173023 SetSomeColumnNotNull: reverting ============
-- remove_check_constraint(:users, {:name=>"users_some_column_null"})
```
Which leads to the error:
```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Table 'users' has no check constraint for {:name=>"users_some_column_null"}
```
I believe this comes about because of the second step, as outlined by the README:

```
Then validate it in a separate migration. A NOT NULL check constraint is functionally equivalent to setting NOT NULL on the column (but it won’t show up in schema.rb in Rails < 6.1). In Postgres 12+, once the check constraint is validated, you can safely set NOT NULL on the column and drop the check constraint.

For Rails 6.1, use:

class ValidateSomeColumnNotNull < ActiveRecord::Migration[7.0]
  def change
    validate_check_constraint :users, name: "users_some_column_null"

    # in Postgres 12+, you can then safely set NOT NULL on the column
    change_column_null :users, :some_column, false
    remove_check_constraint :users, name: "users_some_column_null"
  end
end
```

If run together, the check_constraint will be removed in the `up` of the Validation migration, which then causes the previous migration to be come irreversible.

I would suggest adding the check_constraint back in the second migration `down`, but my concern is that there's a safety issue with that of which I'm unaware of.

```
class ValidateSomeColumnNotNull < ActiveRecord::Migration[7.0]
  def up
    validate_check_constraint :users, name: "users_some_column_null"

    # in Postgres 12+, you can then safely set NOT NULL on the column
    change_column_null :users, :some_column, false
    remove_check_constraint :users, name: "users_some_column_null"
  end
  
  def down
   add_check_constraint :users, "some_column IS NOT NULL", name: "users_some_column_null", validate: false
   change_column_null :users, :some_column, true
  end
end
```

Thank you! Any feedback appreciated!

**Comment by ankane** [comment]
Hey @yakschuss, seems like that should work for the Postgres 12+ case. Feel free to submit a PR.

**Comment by yakschuss** [comment]
Will do, thanks!

**Comment by yakschuss** [comment]
Hi @ankane - I'm having difficulties understanding how to edit the `validate_constraint_code` from a `def change` to a `def up` and a `def down`. I've found [this](https://github.com/ankane/strong_migrations/blob/14e525876c9d0fdf12d84440bb78bca5b1bea1af/lib/strong_migrations/checker.rb#L247) - but could use some further direction. Thank you!

**Comment by ankane** [comment]
Have been moving things around a bit, but just pushed an update to the template so this change will only need to modify `validate_foreign_key_code`.

**Comment by ankane** [comment]
My bad, wrong template. Should be `validate_constraint_code` instead.

**Comment by yakschuss** [comment]
Thanks! Going to work on this this weekend.

**Comment by yakschuss** [comment]
Hi @ankane - 

It seems as though the issue stems from `validate_check_constraint` being run first in both the `up` and `down`, and it will fail if the constraint is not present.

Using [reversible](https://api.rubyonrails.org/v7.0.2.2/classes/ActiveRecord/Migration.html#method-i-reversible) would allow us to only run the validation in the up direction.

```
class ValidateExampleTableExampleColumnNull < ActiveRecord::Migration[6.1]
  def change
    reversible do |direction|
      direction.up { validate_check_constraint :example_table, name: "example_table_example_column_null" }
    end

    change_column_null :example_table, :example_column, false
    remove_check_constraint :example_table, "example_column IS NOT NULL", name: "example_table_example_column_null"
  end
end
```

What do you think?

**Comment by keithlayne** [comment]
I goofed on one of these, and it took a little time to undo it the AR way. On 6.1 at least, I was able to rollback by doing pretty much what @yakschuss suggested:

- put the validation in a reversible up block
- include all the same params to `remove_check_constraint` that I used in the add

In general I've gotten used to copying all the params for reversible things, and confirmed that rollback failed without the `name` option included. It also made sense to me to include `validate: false` - at the end of rollback AFAICT I end up in the same state as before the migration: I have an unvalidated check constraint and a nullable column.

For pre-6.1 I'd think you can just leverage `reversible` for the individual steps and use `execute` there?

**Comment by mattboldt** [comment]
I'm a bit confused why this migration isn't fully reversable. From the Rails docs: https://api.rubyonrails.org/v6.1.0/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_check_constraint
```
remove_check_constraint(table_name, expression = nil, **options)
```
> The `expression` parameter will be ignored if present. It can be helpful to provide this in a migration's `change` method so it can be reverted. In that case, `expression` will be used by `add_check_constraint`.

If `remove_check_constraint` adds the constraint back during a rollback, why is `validate_check_constraint` failing after it? I'm not really sure what the reverse of validating a check constraint would be, but if it's the same in both directions, shouldn't the constraint be present at this point?

**Comment by keithlayne** [comment]
> It seems as though the issue stems from `validate_check_constraint` being run first in both the `up` and `down`, and it will fail if the constraint is not present.

@mattboldt this seems to be the issue - I didn't dig into the AR stuff, but what I saw was consistent with this. IMO the behavior on the AR side should _probably_ be to preserve order and be a no-op on reversal, since you can't un-validate a check constraint :smile_cat:

**Comment by mattboldt** [comment]
I think I found the culprit: `validate_check_constraint` would eventually call `validate_constraint`, which should call `execute`, which _should_ raise `ActiveRecord::IrreversibleMigration` as you'd expect. But, first it calls `check_constraint_for!` which explicitly raises another error related to the constraint:

https://github.com/rails/rails/blob/v6.1.5/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L632-L641

https://github.com/rails/rails/blob/v6.1.5/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1531-L1534

But based on all this, your solution seems perfect -- validating constraints should never need to run during rollback.

**Comment by ankane** [comment]
Just pushed a change to make it reversible. Thanks for reporting!
