### ISSUE TITLE
Consider running arbitrary SQL a dangerous operation

### ISSUE THREAD

**Issue by jturkel** [ankane/strong_migrations#17]
This gem provides awesome protection against dangerous operations when using the Rails migration DSL. Unfortunately it's easy for developers to inadvertently bypass this safety net when running arbitrary SQL e.g.

```
class AddNumWheelsToCars < ActiveRecord::Migration
  def up
    execute('ALTER TABLE cars ADD COLUMN num_wheels integer DEFAULT 4 NOT NULL')
  end

  def down
    remove_column(:cars, :num_wheels)
  end
end
```
It would be great if `execute` was considered a dangerous operation that required developers to explicitly indicate that they know what they're doing. I'd be happy to put up a PR if you're open to the change.

**Comment by ankane** [comment]
Hey @jturkel, great idea. Happy to accept a PR. We do something similar for `change_table`.
