### ISSUE TITLE
[Question] Suggested syntax when removing columns on existing table with Rails 6.1+

### ISSUE THREAD

**Issue by pil0u** [ankane/strong_migrations#179]
Hi @ankane,

Thank you for your general contribution in the Ruby / Rails ecosystem.

I am running on Rails 7 and I want to remove 2 columns at once, which [RuboCop](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsreversiblemigration) tells me to do this way ([related PR](https://github.com/rails/rails/pull/36589)):
``` ruby
class RemoveColumnsFromHouses < ActiveRecord::Migration[7.0]
  def change
    remove_columns :houses, :column_1, :column_2, type: :text
  end
end
```

When I run this migration, I get a (normal) dangerous operation from `strong_migrations`:
```
=== Dangerous operation detected #strong_migrations ===

Active Record caches attributes, which causes problems
when removing columns. Be sure to ignore the columns:

class House < ApplicationRecord
  self.ignored_columns = ["column_1", "column_2", "{:type=>:text}"]
end

Deploy the code, then wrap this step in a safety_assured { ... } block.

class RemoveColumnsFromHouses < ActiveRecord::Migration[7.0]
  def change
    safety_assured { remove_columns :houses, :column_1, :column_2, type: :text }
  end
end
```

More specifically, is this syntax correct? `self.ignored_columns = ["column_1", "column_2", "{:type=>:text}"]`

**Comment by fatkodima** [comment]
That is incorrect syntax, should be `self.ignored_columns = ["column_1", "column_2"]`.

**Comment by ankane** [comment]
Hey @pil0u, thanks for reporting! Fixed in the commit above (should be what @fatkodima wrote).

**Comment by pil0u** [comment]
Woah, that was quick, thank you! Also, congrats on release 1.0 :tada:
