### ISSUE TITLE
questions about add_reference

### ISSUE THREAD

**Issue by jjb** [ankane/strong_migrations#182]
i have a migration like this

```ruby
  disable_ddl_transaction!

  def change
    add_reference :foos, :bar, index: {algorithm: :concurrently}
    add_reference :foos, :baz, index: {algorithm: :concurrently}
  end
```

im using postgres

the first one succeeded, then the second one failed with a lock timeout

trying to run it again, didn't work because first one was attempted again, and of course wasn't rolled back in previous run

1. in general, maybe there should be a warning/recommendation somewhere about doing as few non-ddl actions as possible in a migration to avoid this sort of thing
2. for `add_reference` in particular: is it possible for part of the work (column, fkc, index) to succeed, and another to fail? or is it atomic even with ddl turned off? (i could do my own local experiments to answer this but maybe someone has a more sophisticated view than me on this regardless)

if it's atomic, then my idea in #1 is particularly impactful (but might be a good idea regardless)

**Comment by ankane** [comment]
Hey @jjb, from my understanding, it's possible for `add_reference` to fail during any statement, at which point you'd need to resolve it manually.

Some teams may prefer to keep migrations minimal/break the example above in two migrations to minimize the chance of an issue, but I don't feel strongly enough to recommend it.
