### ISSUE TITLE
Remove index possible bug when safe_by_default

### ISSUE THREAD

**Issue by federicoaldunate** [ankane/strong_migrations#183]
When `safe_by default = true` the `remove_index` may work incorrectly. Some arguments may be missed.

### Context
remove_index method change from 6.0 to 6.1 in Rails

[Remove Index 6.0](https://apidock.com/rails/v6.0.0/ActiveRecord/ConnectionAdapters/SchemaStatements/remove_index)
```ruby
  def remove_index(table_name, options = {})
```
[Remove Index 6.1](https://apidock.com/rails/v6.0.0/ActiveRecord/ConnectionAdapters/SchemaStatements/remove_index)
```ruby
  def remove_index(table_name, column_name = nil, **options)
```

### Problem
In the first line of this method: [checks.rb # def check_remove_index(args)](https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations/checks.rb#L292) some arguments may be lost for versions `ActiveRecord >= 6.1`

#### Note:
I can help trying to figure out a solution

**Comment by ankane** [comment]
Hey @federicoaldunate, thanks for reporting! Fixed in the commit above. It also looks like `safe_by_default` silently ignores extra arguments for `remove_index` and likely other methods, so planning to address that as well.
