### ISSUE TITLE
PostgreSQL 14.x CREATE INDEX CONCURRENTLY issue

### ISSUE THREAD

**Issue by ibrahima** [ankane/strong_migrations#184]
Hi, I heard about this issue with PostgreSQL 14.x and creating indices concurrently. I wonder if it would be possible for strong_migrations to add a rule to prevent creating indices concurrently if the PostgreSQL version is >= 14.0 and < 14.4. I know it's a very limited-time rule (the fixed version is coming out next week) but it might be nice to save people from some trouble if they do happen to be on an affected version and can't upgrade immediately.

https://www.postgresql.org/message-id/165473835807.573551.1512237163040609764%40wrigleys.postgresql.org

Thanks!

**Comment by ankane** [comment]
Hey @ibrahima, thanks for the suggestion! Just pushed 1.2.0 with a new check for it.

**Comment by ibrahima** [comment]
Woah thanks, that was fast!
