### ISSUE TITLE
Suggestion: change the URL for the list of checks in README

### ISSUE THREAD

**Issue by pil0u** [ankane/strong_migrations#194]
Hi,

In the [README](https://github.com/ankane/strong_migrations#disable-checks), you mention a link that should contain a list of keys, but does not.
I found the [`error_messages.rb`](https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations/error_messages.rb) to be more relevant.

Thanks a lot for your work, you rock.

**Comment by ankane** [comment]
Thanks @pil0u!
