### ISSUE TITLE
`safety_assured` error when trying to run with sorbet

### ISSUE THREAD

**Issue by concept47** [ankane/strong_migrations#196]
Hi,

I'm trying to use this gem in a codebase [that uses sorbet ](https://github.com/sorbet/sorbet)
And running `srb tc` which type checks the code base raises this error around the `sorbet_assured` block that is recommended to use around migrations we want to ignore strong_migration checking on

```
db/migrate/ddddddddd_view_migration_ddddddddddd.rb:13: Method safety_assured does not exist on ViewMigrationddddddddddd https://srb.help/7003
    13 |    safety_assured do
            ^^^^^^^^^^^^^^
   ```
   

We have an `sorbet/rbi/gems/strong_migrations@1.2.0.rbi` [file generated that looks like this](https://gist.github.com/concept47/42948eca7453e1ba11315e3b940787c5) 

Just wondering if there were any ideas on how to resolve?

**Comment by ankane** [comment]
Hey @concept47, I haven't used Sorbet, but it looks like you may need to [let it know](https://sorbet.org/docs/error-reference#7003) the method exists on `ActiveRecord::Migration` in an `*.rbi` file.

```ruby
class ActiveRecord::Migration
  def safety_assured; end
end
```

**Comment by concept47** [comment]
Thank you @ankane that did it.
