### ISSUE TITLE
Gem stopped working upon update to Rails 7.0.2

### ISSUE THREAD

**Issue by pauljacksonrodgers** [ankane/strong_migrations#198]
When we upgraded the app to version 7.0.2, the migration checks seem to have stopped running altogether. I've tried both 1.3.0 and 0.8.0, as mentioned in [this](https://github.com/ankane/strong_migrations/issues/171) ticket. We aren't seeing an error though, just that bad migrations do not raise errors anymore. We also aren't using versioned schemas (we use a `structure.sql` file). Has this been reported before? I'm not exactly sure what next steps to take.

**Comment by ankane** [comment]
Hey @pauljacksonrodgers, I'm not sure how to reproduce, but seems like it may be specific to your application. I'd try forking and adding debugging to see what's going on.

**Comment by pauljacksonrodgers** [comment]
@ankane unsurprisingly this was user error 😆

We upgraded to PG11; I didn't realize that adding columns with defaults became safe (even though your documentation clearly says so), so I assumed the gem wasn't running properly.

Sorry to bother!
