### ISSUE TITLE
Safer defaults for lock timeouts

### ISSUE THREAD

**Issue by jturkel** [ankane/strong_migrations#20]
Commit b57486dd7946cfcb0b09792164fd319ffee7f1ba added some helpful suggestions around setting lock timeouts in migrations. The [activerecord-safer_migrations](https://github.com/gocardless/activerecord-safer_migrations) gem provides some nice capabilities to set default lock/statement timeouts and override them on a per-migration basis. Do you think it would be worth adding similar functionality to this gem? I'd love to only include one gem in my projects for safe/strong migrations :)

**Comment by ankane** [comment]
Hey @jturkel, thanks for the suggestion 👍  I don't see a lot of benefit from pulling the functionality into Strong Migrations, so think it's best to just use two gems.
