### ISSUE TITLE
statement_timeout is ignored?

### ISSUE THREAD

**Issue by gingerlime** [ankane/strong_migrations#201]
I'm not sure if it's something new, because I think it worked before, but we recently bumped into this. 

For some reason, even though we configured `StrongMigrations.statement_timeout = 1.hour` in `config/initializers/strong_migrations.rb`, our migrations time-out much faster. We get `PG::QueryCanceled: ERROR:  canceling statement due to statement timeout` 

It looks like it's taking the timeout from our `database.yml` instead of from the strong migrations config? 

config/database.yml:

```ruby
production: &production
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 50
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  variables:
    statement_timeout: 1min
    lock_timeout: 10s
```

config/initializers/strong_migrations.rb:

```ruby
StrongMigrations.lock_timeout = 10.seconds
StrongMigrations.statement_timeout = 1.hour
```

We're using Rails 7.0.4 with the latest version of strong_migrations (1.3.1)

**Comment by ankane** [comment]
Hey @gingerlime, I'm not sure how to reproduce. Are you using PgBouncer or another connection pooler?

**Comment by gingerlime** [comment]
Thanks for getting back @ankane. We don't use PgBouncer nor another connection pooler. Our database is managed by aiven.io so not sure if they apply some constraints automatically somewhere?

I can work around it with something like this:

```ruby
def up
  safety_assured do
    old_value = query_value("SHOW statement_timeout")
    execute "SET statement_timeout TO '1h'"

    # migration code

    ensure
      execute("SET statement_timeout TO #{quote(old_value)}")
    end
  end
end
```

But this is what strong_migrations is doing anyway, as far as I can tell, so this is definitely odd. I guess it would rule out something that aiven.io is enforcing on the database, right?

I was trying to reproduce this but I'm also struggling at the moment :-/ (at least with `execute "select pg_sleep(65)"`), even when testing on staging. I guess we can close this for now, and I can re-open if I can reproduce it. If you have some suggestions or tips on how to test some things, I'd be very grateful :)

**Comment by ankane** [comment]
Aiven offers [connection pooling](https://docs.aiven.io/docs/products/postgresql/concepts/pg-connection-pooling.html), so I'd check if you're using that. If so, you'll need to [set the timeouts](https://github.com/ankane/strong_migrations#migration-timeouts) on the database user instead of in the initializer (otherwise, it'll cause the behavior you're describing).

**Comment by gingerlime** [comment]
When trying to reproduce it on staging, I noticed that I can see debug statements that set the statement and lock timeout after the transaction starts as part of the migration. It looks something like this (truncated for brevity)

```
DEBUG name=ActiveRecord message=TRANSACTION payload={"sql":"BEGIN" ...
DEBUG name=ActiveRecord message= payload={"sql":"SHOW server_version_num" ...
DEBUG name=ActiveRecord message= payload={"sql":"SET statement_timeout TO 3600000" ...
DEBUG name=ActiveRecord message= payload={"sql":"SET lock_timeout TO 10000" ...
```

And these are the correct values (1h statement timeout, 10s lock timeout), and the migration works as expected and doesn't time out.

I then looked-up the logs from when our failed migrations on staging, and oddly I didn't see those SETs after the transaction started in the debug log (it was noisy, but I'm pretty sure they weren't executed, which would also explain why the migration times-out). 

At the moment when I try to deploy / run migrations on staging, it does execute those statements, so it's like the problem disappeared. But can't put my finger on what might cause these statements *not* to execute some times.

**Comment by ankane** [comment]
Don't have any other ideas besides a connection pooler, but seems like it may be specific to your application. I'd recommend forking and adding debugging to try and figure out what's going on.

**Comment by gingerlime** [comment]
Thanks for getting back to me @ankane. We'll definitely keep an eye on it and forking the gem to add more debugging sounds like a good idea.

A connection pooler might be a good idea as well, regardless, I guess. Even though we probably didn't hit a scaling issue there yet. If we do use it, how do you recommend running migrations via a different database user than the app itself? using a different environment for migrations? (sorry if it's over-extending your courtesy and asking too much)

**Comment by ankane** [comment]
I'd wait until you need it since it adds complexity, but you could use either a different environment or ERB logic to switch between credentials in `database.yml` (a different server/environment can make it so app servers don't have access to migration credentials).

Also, here's how you can [set up permissions](https://ankane.org/postgres-users) for users.

**Comment by gingerlime** [comment]
Thank you so much @ankane 🙏
