### ISSUE TITLE
[Idea] `change_table` support

### ISSUE THREAD

**Issue by ohbarye** [ankane/strong_migrations#204]
Hi, this might be a question rather than a new idea.

I know this gem doesn't support `change_table` since the [first commit](https://github.com/ankane/strong_migrations/commit/b1d7fee03f9be59b4175ad8fd02ac7959a6c8466#diff-dc7411319ecabaa1d5f4e96f2419b5d119e8ca1374285687617da6cc2fbef384R18-R19) and I saw @ankane state "Strong Migrations doesn't support inspecting operations inside a `change_table` block" in [this comment](https://github.com/ankane/strong_migrations/issues/158#issuecomment-896535321).

My question is, is it a policy of this gem to not support `change_table`, or is there any technical problem to support it?

Please feel free to close this issue if it's not the right direction for this gem to support it.

**Comment by ankane** [comment]
Hey @ohbarye, since most* `change_table` operations can be written as individual operations, I'm hesitant to add the complexity to support it. Also, I haven't seen it used much in practice compared to individual operations.

\* `change_table(table, bulk: true)` allows you to combine multiple operations into a single statement, but for Postgres, there's not much benefit over individual statements inside a transaction.

**Comment by ohbarye** [comment]
Thanks for your comment. I understand your stance and agree with the direction. 👍 

💭 AFAIK the only benefit of `change_table` over individual operations is `bulk: true` for MySQL or other DB that doesn't support DDL transactions. I think a project using those DBs inclined to use `change_table(table, bulk: true)` to tidy up DDLs.

**Comment by G-Rath** [comment]
Just flagging that [rubocop does enforce using `change_table` by default](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsbulkchangetable), and we've got a number of uses across a number of applications at my work so would appreciate support for this if it is possible.

It looks like @korny has made a start on this - it would be awesome to know if there's anything we can do to help with that

**Comment by korny** [comment]
I would also like to continue with this PR and get it to a state which can be used at my company. As for support: Writing/generating a set of specs would be great help! It’s not that hard to make the feature work, but tricky to get perfect. Maybe we can collaborate ☺️
