### ISSUE TITLE
Using in a non-Rails application

### ISSUE THREAD

**Issue by fade2black** [ankane/strong_migrations#209]
I have a non rails application where I use the `activerecord` gem and migration tasks.  Any idea how to use it in a non Rails (pure Ruby app) application? 

As far as I understand we generate an initializer, but I am not sure how to correctly get it worked when we run `rake db:migrate`. :-)

**Comment by ankane** [comment]
Hey @fade2black, as far as I know, it should just work when it's included and Active Record is loaded. https://github.com/ankane/strong_migrations/blob/4a22176cb5e2cd320b365c6d2fb2ae0333caec78/lib/strong_migrations.rb#L89

**Comment by fade2black** [comment]
@ankane, thank you for your quick response. :-)
Let me try.
