### ISSUE TITLE
[Idea] Safely removing a column default value

### ISSUE THREAD

**Issue by bensheldon** [ankane/strong_migrations#211]
Rails will load and cache the database schema at application startup, which contains columns with default values. When creating new records, Active Record will not INSERT attribute values that match the database column default value. During the period between the database migration being run to remove the column default value, and the Rails application being restarted and schema cache reloaded, records can end up with unexpected null values.

Here's what happens when there is a default value that matches the attribute value:

```ruby
create_table :users do |t|
  t.string :name, default: "Alice"
end

User.create!(name: "Alice") # => INSERT INTO \"users\" DEFAULT VALUES;
```

The solution, as far as I have discovered, is to call `{COLUMN}_will_change!` to force Active Record to update the attribute:

```ruby
class User < ActiveRecord::Base
  after_initialize do
    name_will_change! if !persisted?
  end
end

User.create!(name: "Alice") # => INSERT INTO \"users\" (\"name\") VALUES (?) 
```

...which, in a similar pattern to `ignored_columns`, should be deployed prior to the migration that removes the default value:

```ruby
change_column_default :users, :name, from: "Alice", to: nil
```

Here's a quick gist if you want to play around with it: https://gist.github.com/bensheldon/4bd371ac900eaa3f6d0f131815163d06

The idea here is to enforce a `safety_assured` block around `change_column_default` for the change to `nil`.

**Comment by bensheldon** [comment]
Thinking about this some more, _any_ change to an existing column default value is unsafe without forcing `_will_change!`

**Comment by ankane** [comment]
Hey @bensheldon, thanks for sharing. Will dig into this when I have a chance.

**Comment by fatkodima** [comment]
Gitlab tried to solve the same problem - https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/models/concerns/safely_change_column_default.rb

**Comment by zacharysierakowski** [comment]
@bensheldon @ankane @fatkodima any update here? I'd be interesting in helping to get a solution out there for us. Given the current focus on availability, I think this area/problem is applicable and pretty important.

**Comment by bensheldon** [comment]
@zacharysierakowski whoops! I think our internal GitHub discussion about this has leaked into a community gem issue.

**Comment by zacharysierakowski** [comment]
@bensheldon oof, I apologize for crossing threads! I'll reach out to you directly to chat more about the internal GitHub specifics here. I went ahead and hid my two comments and marked them as "off topic" 🙂

**Comment by ankane** [comment]
Hi all, added a check for this in the commit above. It uses `before_create` instead of `after_initialize` so `record.changed?` is accurate before saving.

Thanks for the suggestion and discussion!

**Comment by bensheldon** [comment]
@ankane thank you! 🎉

**Comment by ankane** [comment]
Just discovered there's a setting for this (`config.active_record.partial_inserts` in Rails 7 and `config.active_record.partial_writes` in Rails < 7), so that's probably a better recommendation.

In Rails 7, partial inserts are disabled by default (https://github.com/rails/rails/pull/42769), making things safe by default.

cc @cscorley

**Comment by ankane** [comment]
Updated the check and recommendation in the commit above. Feel free to share any thoughts.

**Comment by bensheldon** [comment]
@ankane Can you try to verify that the configuration works on the reproduction gist I shared? I'm not observing that `ActiveRecord::Base.partial_inserts = false` changes the behavior in a beneficial way.

**Comment by bensheldon** [comment]
@ankane oops, I wasn't actually changing the value in the script. I did verify that it is inserting the value even if it matches the column default.

`ActiveRecord::Base.partial_inserts = false` is 👍🏻
