### ISSUE TITLE
Consider adding `reset_column_information` to Backfilling data recommendations

### ISSUE THREAD

**Issue by alexeyr-ci1** [ankane/strong_migrations#214]
When we follow [Backfilling data: Good](https://github.com/ankane/strong_migrations#good-2), we found that sometimes when the migrations run immediately one after another, cached column information seems to be used and `User.reset_column_information` needs to be used in the second migration. 

Unfortunately, this is hard to reproduce. In our project it happened when adding a translation column with the [`mobility`](https://github.com/shioyama/mobility) gem and backfilling it from the non-translation column.

**Comment by niudage** [comment]
good

**Comment by ankane** [comment]
Hi @alexeyr-ci1, thanks for the suggestion, and sorry for the delay. From my understanding and experience, this seems extremely unlikely to both happen and cause issues (the backfill example with `update_all` should work even if Active Record has outdated column information), but if you have specifics about the migrations and the issue it caused, happy to think about it more.

**Comment by ankane** [comment]
Thinking about it more, a note is probably good for backfills that don't use `update_all`, so added in the commit above. Thanks for the suggestion.
