### ISSUE TITLE
[Idea] Suggest adding if_not_exists when creating concurrent indexes?

### ISSUE THREAD

**Issue by DanMegaGamer** [ankane/strong_migrations#223]
Firstly thanks for your work on this, it's really useful.

I recently came across an issue when adding an index.

Strong Migrations suggested adding `algorithm: :concurrently` and  `disable_ddl_transaction!` which was great.

The migration failed in production due to some data violating it, but the index was created and not rolled back on failure I assume because of `disable_ddl_transaction!`.

After removing the row that violated the index it then wasn't possible to run the migration as the index existed.

Would it make sense to suggest including if_not_exists if `disable_ddl_transaction!` is used with index creation in Rails >= 6.1.

```
=== Dangerous operation detected #strong_migrations ===

Adding an index non-concurrently blocks writes. Instead, use:

class AddTestIndex < ActiveRecord::Migration[7.0]
  disable_ddl_transaction!

  def change
    add_index :memberships, [:email], unique: true, algorithm: :concurrently, if_not_exists: true
  end
end
```

**Comment by fatkodima** [comment]
When concurrent creation of the index fails, it leaves invalid index behind, which definitely exists, but will not be used by the database. So `if_not_exists` won't correctly work in this case.

The better approach is something like:
```ruby
remove_index :memberships, [:email], unique: true, if_exists: true
add_index :memberships, [:email], unique: true, algorithm: :concurrently
```

In newest rails it is even possible if invalid index exists: https://github.com/rails/rails/pull/45160.

**Comment by fatkodima** [comment]
In my alternative to this gem, I made `add_index` idempotent with this check - https://github.com/fatkodima/online_migrations/blob/3ab28fd0d4de831e877122798fe4441698f9cd59/lib/online_migrations/schema_statements.rb#L702-L731

**Comment by DanMegaGamer** [comment]
Thanks @fatkodima that's really useful to know, I just checked and the index isn't working as you said, so I'll remove and add again.
