### ISSUE TITLE
add_reference ignores index: false if foreign_key is set

### ISSUE THREAD

**Issue by Skulli** [ankane/strong_migrations#226]
I have the following migration

    add_reference :log_entries, :log_day, null: true, index: false, foreign_key: {to_table: "log_days"}

Without strong migrations everything is fine. 

     add_reference(:log_entries, :log_day, {:null=>true, :index=>false, :foreign_key=>{:to_table=>"log_days"}})

With enabled gem

    add_reference(:log_entries, :log_day, {:null=>true, :index=>{:algorithm=>:concurrently}})
    add_foreign_key(:log_entries, "log_days", {:column=>"log_day_id", :validate=>false})
    validate_foreign_key(:log_entries, "log_days", {:column=>"log_day_id"})

and the schema shows, that a index is created. If i just set `foreign_key: true`, it works

Using ruby 3.2.2 and rails 7.0.4 on postgres 14

**Comment by Skulli** [comment]
Odd, just checked the database via psql and its not showing the index. The schema does show it though. The gem `annotate` does show it too.

**Comment by ankane** [comment]
Hi @Skulli, thanks for reporting! Pushed a fix in the commit above. However, I think it may make sense to have a separate check for adding a foreign key [without an index](https://www.cybertec-postgresql.com/en/index-your-foreign-key/).
