### ISSUE TITLE
[Idea] Consider adding check for change_column_default(..., to: nil)

### ISSUE THREAD

**Issue by cscorley** [ankane/strong_migrations#232]
Hi friends,

Thank you for this project, it has been incredibly useful for me.

Recently we had an incident that I think could be a good migration candidate.

Context:  We use Doorkeeper to issue OAuth2 tokens.  We set this up initially to only issue tokens to Users, but have recently found the need to have more than one resource owner type. So, we went to enable the Doorkeeper option `use_polymorphic_resource_owner` which would allow this use case.  By default, with this option off, Doorkeeper only creates tables that have a column `resource_owner_id` and no `resource_owner_type`.  We are using Rails 6.1.7.3 and Doorkeeper 5.6.6.  We run database migrations before we start our deployment rollouts.

To achieve this, our strategy was over three deploys:

1. Create a migration which added `resource_owner_type` with default value as `"User"`.  Below is the migration, and it is pretty close to the Doorkeeper generated one with exception to the default value.  We chose to use a default value on column creation due to the scale of our tables.
```ruby
class EnablePolymorphicResourceOwner < ActiveRecord::Migration[6.1]
  def change
    add_column :oauth_access_tokens, :resource_owner_type, :string, default: 'User'
    add_column :oauth_access_grants, :resource_owner_type, :string, null: false, default: 'User'

    add_index :oauth_access_tokens,
              [:resource_owner_id, :resource_owner_type],
              name: 'polymorphic_owner_oauth_access_tokens'

    add_index :oauth_access_grants,
              [:resource_owner_id, :resource_owner_type],
              name: 'polymorphic_owner_oauth_access_grants'
  end
end
```
2. Turn on `use_polymorphic_resource_owner` in the Doorkeeper init
3. Remove the default value for `resource_owner_type`
```ruby
class RemoveDoorkeeperDefaultColumns < ActiveRecord::Migration[6.1]
  def change
    change_column_default(:oauth_access_tokens, :resource_owner_type, from: "User", to: nil)
    change_column_default(:oauth_access_grants, :resource_owner_type, from: "User", to: nil)
  end
end
```

The migrations itself when OK, but the "gotcha" we ran into when deploying step 3 is that during the rollout, there were still Rails instances from step 2 after the database migration for step 3 had already ran.  These Rails instances still had an old schema.rb + cache that thought the column had a default of "User" -- while the database no longer had the default.  Naturally, ActiveRecord  does not send values for those columns for newly created objects when the values match the default (by my testing on 6.1.7.3), even if the objects are instantiated with explicit values.  (It may also do this with changes to other non-nil values, I did not test, but assume it would)

So, Rails instances that had not been updated yet with the latest schema.rb were creating rows that had nil for `resource_owner_type`, which in turn breaks polymorphic lookups.  I'm not sure of what the alternative would have been for us in this case (other than we should have done a separate backfill instead of the above 3 steps), but just know it's worth avoiding step 3 in the future.

Thanks!

**Comment by ankane** [comment]
Hi @cscorley, thanks for the suggestion and detailed report! Added a check in the commit above (related: #211).

**Comment by cscorley** [comment]
Thanks so much!  Now I know I can just force pass the value to the database. 😄
