### ISSUE TITLE
lock_timeout + lock_timeout_retries + concurrent postgres indexes

### ISSUE THREAD

**Issue by grk** [ankane/strong_migrations#233]
I'm not even sure if this is a bug, but I ran into the following situation this morning:

1. I have strong_migrations configured with `lock_timeout = 10.seconds` and `lock_timeout_retries = 3`.
2. I have a migration that concurrently adds index to a busy table:
    ```ruby
    disable_ddl_transaction!

    def change
      add_index :some_table, %i(col1 col2), name: "index_some_table_on_col1_and_col2", algorithm: :concurrently
    end
    ```
3. During the deploy, the migration fails to acquire a lock:
    ```
    Migrating to SomeMigrationThatAddsIndex (20230721150045)
    == 20230721150045 SomeMigrationThatAddsIndex: migrating =============
    -- add_index(:some_table, [:col1, :col2], {:name=>"index_some_table_on_col1_and_col2", :algorithm=>:concurrently})
    -- Lock timeout. Retrying in 10 seconds...
    -- add_index(:some_table, [:col1, :col2], {:name=>"index_some_table_on_col1_and_col2", :algorithm=>:concurrently})
    rails aborted!
    StandardError: An error has occurred, all later migrations canceled:
    PG::DuplicateTable: ERROR:  relation "index_some_table_on_col1_and_col2" already exists
    ```
4. According to postgres docs, this is to be expected - any errors during concurrent index creation leave behind an invalid index (which makes sense since this was executed with `disable_ddl_transaction!`), and that index can be deleted or reindexed concurrently.
5. I worked around this by reindexing by connecting directly with psql and altering the migration by adding `if_not_exists: true`.

I wonder if this is something that could be solved in scope of this gem. Maybe a safety warning that concurrent index creation + lock_timeout can lead to this scenario?

---

For reference, used versions:
* PostgreSQL 14.7 (Ubuntu 14.7-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
* Ruby 3.2.2
* Rails 7.0.6
* strong_migrations 1.6.0

**Comment by quentindemetz** [comment]
FWIW I've patched `add_index` to remove invalid indexes if the command fails 💡

**Comment by HarlemSquirrel** [comment]
I think it could be nice to have this gem at least recommend if not require using `if_not_exists: true` for adding indexes. 

I guess the main risk is trying to add a new index with the same name as an existing index but with different parameters and not realizing the new index is quietly skipped.

**Comment by ankane** [comment]
Added an experimental `remove_invalid_indexes` option in the commit above that will remove the invalid index before retrying.

```ruby
StrongMigrations.remove_invalid_indexes = true
```

I think it'll be useful for users retrying migrations manually, as well as with `lock_timeout_retries`. Let me know if anyone tries it and has any feedback.

@jjb Whether or not an index is left behind depends on the lock mode that's blocking it. `ACCESS EXCLUSIVE` won't leave behind an invalid index, while `ROW EXCLUSIVE` will.

**Comment by thecoolestcoderrushil** [comment]
The busy-table concurrent-index failure and invalid-index retry path is a great example of a migration risk static checks cannot fully predict. We’re building pre-merge execution checks against production-shaped Postgres. Would this have helped in your deploy workflow?
