### ISSUE TITLE
[Idea] Checks for dangerous attributes

### ISSUE THREAD

**Issue by aditya-cherukuri** [ankane/strong_migrations#237]
Recently I noticed that you can inadvertently add a dangerous attribute via a migration and only end up with exceptions when you try to use it in your application code. Something like this:

`ActiveRecord::DangerousAttributeError: changes is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.`

Though it is not really a check against dangerous migrations I felt it might be a good addition here as having a rubocop rule might not really help or be too late.

**Comment by ankane** [comment]
Hi @aditya-cherukuri, thanks for the suggestion. This should show up pretty quickly in development, so I don't think a check is needed (but users could use a custom check for this).
