### ISSUE TITLE
Instructions for adding a column with a default value are different in README and in the warning message

### ISSUE THREAD

**Issue by Thau** [ankane/strong_migrations#24]
The instructions for adding a column with a default value in the README are:

```
1. Add the column without a default value
2. Add the default value
3. Commit the transaction
4. Backfill the column
```

Meanwhile, running an unsafe migration will return this list of instructions:

```
1. Add the column without a default value
2. Commit the transaction
3. Backfill the column
4. Add the default value
```

I think the console instructions are correct, because you need to commit the transaction before adding the default value, or the DB will start backfilling inside the transaction, probably locking.

**Comment by ankane** [comment]
Hey @Thau, they are consistent on master. The readme has the new recommended approach.

**Comment by Thau** [comment]
You're right, the reason of the confusion is that this is not yet in a release, but fair enough, thanks for the explanation. We'll use this new approach from now on!
