### ISSUE TITLE
add_reference + index +disable_ddl_transaction! is an unsafe pattern?

### ISSUE THREAD

**Issue by DmitryTsepelev** [ankane/strong_migrations#240]
Hey!

Looks like I found an interesting behavior:

```
class Something < ActiveRecord::Migration[7.0]
  disable_ddl_transaction!

  def change
    add_reference :users, :email, index: { algorithm: :concurrently }
  end
end
```

Effectively it does the following:
1. turns off the transaction (for index)
2. adds column
3. creates index

However, if something goes wrong and migration will fail during the index creation—there will be a weird state: migration is rolled back, column is created, index is not created/created with error.

Do I miss something? I'd be happy to add a new rule for that

**Comment by ankane** [comment]
Hi @DmitryTsepelev, see #202 for a previous discussion.
