### ISSUE TITLE
[Idea] Apply `safety_assured` through `revert`

### ISSUE THREAD

**Issue by keithlayne** [ankane/strong_migrations#242]
Here's an example of what I tried to do:

```rb
class RevertAddBarToFoos < ActiveRecord::Migration[7.0]
  def change
    revert AddBarToFoos # add a column, just what it sounds like
  end
end
```

This triggers the column removal lint, as expected. However, wrapping that in `safety_assured` still triggers the lint.

Obviously there's a straightforward workaround here, but I thought I'd bring it up. 

I have no idea if this is really feasible, and if so, whether it's a good idea or not. It just surprised me a tiny bit, and I couldn't find any prior discussion of this.

(IRL I'm doing some wholesale reverts for reasons. I don't wanna talk about it 😿)

**Comment by ankane** [comment]
Hi @keithlayne, thanks for the suggestion! Pushed this change to the [revert branch](https://github.com/ankane/strong_migrations/compare/revert), but want to think about it a bit more before merging.

**Comment by ankane** [comment]
Merged in the commit above
