### ISSUE TITLE
Adding a column with a default value should is safe when use mysql(5.7) as database

### ISSUE THREAD

**Issue by OuYangJinTing** [ankane/strong_migrations#247]
[In mysql(5.7) doc](https://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl-operations.html#online-ddl-column-operations)
![image](https://github.com/ankane/strong_migrations/assets/33079237/00e10d3b-7a6d-4b2d-8259-a765ca2fdd04)

In strong_migrations README.md, [Adding a column with a default value](https://github.com/ankane/strong_migrations/tree/v1.6.4?tab=readme-ov-file#adding-a-column-with-a-default-value)
![image](https://github.com/ankane/strong_migrations/assets/33079237/fff070cb-acdb-448f-a634-8cb9728a79d5)

**Comment by ankane** [comment]
Hi @OuYangJinTing, thanks for reporting (and sorry for the delay)! Fixed in the commit above.

**Comment by silva96** [comment]
It also has an `*` that says 

Concurrent DML is not permitted when adding an auto-increment column. Data is reorganized
substantially, making it an expensive operation. At a minimum, ALGORITHM=INPLACE, LOCK=SHARED
is required.

in rails at least, it's almost the default to have the autoincrement, so this is not safe by default, or I'm missing something?

**Comment by ankane** [comment]
`add_column ..., default: "default_value"` doesn't add an auto-incrementing column (and there's a separate check for `add_column ..., :primary_key`, which does).

**Comment by silva96** [comment]
> `add_column ..., default: "default_value"` doesn't add an auto-incrementing column (and there's a separate check for `add_column ..., :primary_key`, which does).

Oh gotcha, I somehow misunderstood it like "adding a column in a table that has an autoincrement" my bad.

**Comment by OuYangJinTing** [comment]
Thank.
