### ISSUE TITLE
[Idea] Show check link with error message

### ISSUE THREAD

**Issue by ybiquitous** [ankane/strong_migrations#248]
Hi, thanks for the nice gem! 👋🏼

Sometimes, I'd like to see a detailed description or guidance with an error message. Then, I try finding a section related to the error in `README.md`.

If a link to the section was shown like this, we could visit it with one click:

```diff
 === Dangerous operation detected #strong_migrations ===

 Active Record caches attributes, which causes problems
 when removing columns. Be sure to ignore the column:

 class User < ApplicationRecord
   self.ignored_columns = ["name"]
 end

 Deploy the code, then wrap this step in a safety_assured { ... } block.

 class RemoveColumn < ActiveRecord::Migration[7.1]
   def change
     safety_assured { remove_column :users, :name }
   end
 end

+For more details, see https://github.com/ankane/strong_migrations#removing-a-column 
```

What do you think about this idea? Thanks.

**Comment by ankane** [comment]
Hi @ybiquitous, thanks for the suggestion. The error message should have the relevant details, so I don't think this is needed.
