### ISSUE TITLE
Timeout when using `add_column` with `enum` type

### ISSUE THREAD

**Issue by davidwessman** [ankane/strong_migrations#249]
We ran the following migration in production:

```ruby
class AddsEnumToBlobs < ActiveRecord::Migration[7.0]
  def change
    create_enum(
      :blob_type,
      %w[first second third]
    )

    add_column(
      :blobs,
      :blob_type,
      :enum,
      enum_type: "blob_type",
      default: "first",
      null: false
    )
  end
end
```

and it locked the table, which we have been blessed from since following the gem.

I am not sure why it is locking, but I guess this case needs to be added to unsafe migrations.

Versions:
- `postgres`: 14.9
- `strong_migrations`: 1.6.4
- `rails`: 7.0.8

**Comment by ankane** [comment]
Hi @davidwessman, timeouts can happen with any operation and are designed to protect the DB (they don't indicate an operation is unsafe).

**Comment by davidwessman** [comment]
Even if it was a `PG::LockNotAvailable: ERROR:  canceling statement due to lock timeout`?
I thought it might be since I added a default-value and that it is not possible without locking the whole table if the default value is an enum.
