### ISSUE TITLE
`add_reference` with concurrent index can be dangerous

### ISSUE THREAD

**Issue by Jetbo** [ankane/strong_migrations#250]
Howdy,

I think section for [adding-a-reference](https://github.com/ankane/strong_migrations/blob/d719be7e55e9c2a538ce932ff5f3fd461aa977a1/README.md?plain=1#L437-L465) could be improved. For Postgres, it can cause a broken migration, as I have just recently found out.

The problem is that [add_reference](https://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference) is [a multi-step operation](https://github.com/rails/rails/blob/5d0ab554e3286fe02ae795914ccc23e92f2c73b1/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L216-L228).

`add_reference` creates the column, then the index, then the foreign key. Since `disable_ddl_transaction!` is recommended when trying to add a reference with a concurrent index, the table can put into a partially migrated state with no automatic way to rollback since transactions were disabled.

---

For example,

```ruby
class AddReferenceToUsers < ActiveRecord::Migration[7.1]
  disable_ddl_transaction!

  def change
    add_reference :users, :city, index: {algorithm: :concurrently}
  end
end
```

Would add the column `city_id` on `users` and then attempt to create the index. This indexing operation could fail due to a reason such as `ActiveRecord::LockWaitTimeout: PG::LockNotAvailable: ERROR:  canceling statement due to lock timeout`. The column will remain even though the index failed since transactions are disabled. Re-running the migration will fail since Rails does not expect `city_id` on `users` to already exist.

---

I suggest that the recommendation for adding a reference with a concurrent index for Postgres is changed to this:

```ruby
class AddCityToUsers < ActiveRecord::Migration[7.1]
  def change
    add_column :users, :city_id, :bigint
  end
end
```

```ruby
class AddCityIndexToUsers < ActiveRecord::Migration[7.1]
  disable_ddl_transaction!

  def change
    add_index :users, :city_id, index: {algorithm: :concurrently}
  end
end
```

This way the index creation can be re-attempted separate from the column creation. Safe migration.

**Comment by Jetbo** [comment]
Something like this would also work

```ruby
class AddCityToUsers < ActiveRecord::Migration[7.1]
  def change
    add_reference :users, :city, index: false
  end
end
```

```ruby
class AddCityIndexToUsers < ActiveRecord::Migration[7.1]
  disable_ddl_transaction!

  def change
    add_index :users, :city_id, index: {algorithm: :concurrently}
  end
end
```

**Comment by ankane** [comment]
Hi @Jetbo, check out #202 and #240.
