### ISSUE TITLE
`StrongMigrations.start_after` does not work

### ISSUE THREAD

**Issue by svobom57** [ankane/strong_migrations#253]
## The issue
Hi,
I'm trying to run my old migrations and even though I set up the initializer with the latest timestamp of my migration, I get an error on an old unsafe migration:

My initializer:
```ruby
StrongMigrations.start_after = 2024_01_09_113425
```

```bash
StrongMigrations::UnsafeMigration: 
=== Possibly dangerous operation #strong_migrations ===

Strong Migrations does not support inspecting what happens inside a
change_table block, so cannot help you here. Please make really sure that what
you're doing is safe before proceeding, then wrap it in a safety_assured { ... } block.

db/migrate/20190729122520_add_fields_to_stations.rb:2:in `<class:AddFieldsToStations>'
db/migrate/20190729122520_add_fields_to_stations.rb:1:in `<main>'

```

Now from what I've managed to debug, it seems like the version is being passed down as `nil` here into the checker:
https://github.com/ankane/strong_migrations/blob/9f4dbfbb9443ad71746a26b43ad7bf2d59c7f9e8/lib/strong_migrations.rb#L80

If I follow where that comes from it seems like here, in the Rails code, the `migration` is still the `Proxy` migration with a proper version set:

https://github.com/rails/rails/blob/c6ef898246db2fbc62cfb32f18e313b3fa5438e2/activerecord/lib/active_record/migration.rb#L1527

```ruby
#<struct ActiveRecord::MigrationProxy name="AddFieldsToStations", version=20190729122520, filename="db/migrate/20190729122520_add_fields_to_stations.rb", scope="">
```

But something below in the `ddl_transaction` method calls the `StrongMigrations` gem and raises an error since `version` becomes `nil` there...

I'm wondering why there's defaulting in the code that makes the `version` `nil` anyway. Do you know whether there are any conditions in which Rails would pass the `version` as `nil` or do you think that this might be issue with `strong_migrations` gem itself? I appreciate that this might be hard to reproduce...

## What versions I'm running?
- Strong migrations `1.7.0`
- Rails `7.0.7.2` (with ActiveRecord of the same version)

**Comment by ankane** [comment]
Hi @svobom57, version can be `nil` if an operation is defined on the migration instead of inside `def up` or `def change` (#88).

```ruby
class SomeMigration < ActiveRecord::Migration[7.1]
  change_table ...
end
```

You'll want to use this instead for version checking to work.

```ruby
class SomeMigration < ActiveRecord::Migration[7.1]
  def change
    change_table ...
  end
end
```
