### ISSUE TITLE
[Idea] safety_assured should require justification

### ISSUE THREAD

**Issue by bessey** [ankane/strong_migrations#257]
I try to encourage devs to justify why they are ok to use `safety_assured` in a migration. E.g:

```ruby
  def change
    # table not yet in use in production
    safety_assured { add_column :foo, :bar, :boolean, null: false, default: false }
  end
```

This seems to me like something that should be baked into the gem. Either via a Rubocop check for a proceeding comment, or, more simply, by making it part of the API itself:

```ruby
  def change
    safety_assured(because: "table not yet in use in production") do
      add_column :foo, :bar, :boolean, null: false, default: false
    end
  end
```

**Comment by ankane** [comment]
Hi @bessey, thanks for the suggestion. See #165 for a previous discussion. I'm not sure it's something I'd like to include, but if you decide to fork and try it out with your team, please share how it goes.

Someone could also write a Rubocop check for it outside of the project.
