### ISSUE TITLE
[Idea] Adding auto incrementing primary key does not guarantee that replicas generate the same primary key values (MySQL)

### ISSUE THREAD

**Issue by kpalmvik** [ankane/strong_migrations#258]
## Summary

Adding a primary key to a table does not guarantee that existing rows get the same primary key values in the primary and secondary MySQL replica database.

## Background
To connect our models `Author` and `Book` (using names from a classic Rails example) we added a migration like this:

```ruby
create_table :authors_books, id: false do |t|
  t.references :author, foreign_key: true, null: false
  t.references :book, foreign_key: true, null: false
end
```

After adding data for a short while, we realized that [using `has_many :through` would not work without a primary key on the `authors_books` table](https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many):

>While `has_and_belongs_to_many` suggests creating a join table with no primary key via `id: false`, consider using a composite primary key for the join table in the `has_many :through` relationship. For example, it's recommended to use `create_table :manifests, primary_key: [:assembly_id, :part_id]` in the example above.

This became obvious when Rails couldn't figure out how to delete a specific author-book association, since there was no primary key specified. Instead Active Record issued incorrect SQL statements  causing errors:

```
(ActiveRecord::StatementInvalid) "Mysql2::Error: Unknown column 'authors_items.'
```
Note the missing primary key name after `authors_items.`.

For _reasons_ we decided to keep the `has_many :through` relationship and instead add a generated primary key field (since we are not yet using Rails 7.1 where composite primary keys are supported).

This was done through a migration like:

```ruby
add_column :books_authors, :id, :primary_key
```

**The migration was not flagged as unsafe**, and also ran successfully in both the local environments and when applied to the production database. We could verify that afterwards all rows had an automatically assigned integer primary key from the auto incrementing sequence.

However, soon after the secondary replica started issuing errors like:

```
Could not execute Delete_rows event on table some_database.authors_books;
Cannot delete or update a parent row: a foreign key constraint fails
(some_database.authors_books, CONSTRAINT fk_rails_12345678 FOREIGN KEY (book_id) REFERENCES books (id)),
Error_code: 1451; handler error HA_ERR_ROW_IS_REFERENCED;
```

Long story short, this was **because the primary key that was added had different values generated in the primary database compared to the replica**.

The referential integrity checks from the foreign key constraint prevented the incorrect row from being deleted, even though it had the "correct" primary key value from the primary.

This behaviour is documented in [MySQL: 4.1.1 Replication and AUTO_INCREMENT](https://dev.mysql.com/doc/mysql-replication-excerpt/8.3/en/replication-features-auto-increment.html#:~:text=Adding%20an%20AUTO_INCREMENT,rows%20were%20inserted.):

>Adding an `AUTO_INCREMENT` column to a table with `ALTER TABLE` might not produce the same ordering of the rows on the replica and the source. This occurs because the order in which the rows are numbered depends on the specific storage engine used for the table and the order in which the rows were inserted.

## Discussion

While adding a primary key to an existing table is probably not a very common operation, the resulting behaviour was somewhat unexpected when looking at it from the migration/application level.

Consider if it would make sense to document and/or flag this as an unsafe operation.

**Comment by ankane** [comment]
Hi @kpalmvik, thanks for sharing. Are you using statement-based replication?

**Comment by ankane** [comment]
It looks like this also causes the table to be rewritten, so added a check in the commit above.

**Comment by ankane** [comment]
If that's the case, then something else was probably the cause.
