### ISSUE TITLE
Getting an error complaining about MariaDB Version

### ISSUE THREAD

**Issue by wleeper** [ankane/strong_migrations#261]
I have an application using mysql2 driver, strong_migration 1.8.0 and a MariaDB 10.4 running in a Docker container.

When I run a migration I get the following error:

```
MariaDB version (5.7) not supported in this version of Strong Migrations (1.8.0)
```

I have installed MariaDB locally using Homebrew and it still gives this error, although i am connecting to the Docker database still.

Is there a known issue or configuration issue with this approach.  I will probably abandon the Docker database in favor of a local one at some point anyway, but wanted to see if I could fix this easily first.

**Comment by ankane** [comment]
Hi @wleeper, it may be an issue with version parsing. What does `SELECT VERSION()` return?

**Comment by ankane** [comment]
Also, make sure `StrongMigrations.target_mariadb_version` isn't set to 5.7.

**Comment by wleeper** [comment]
> StrongMigrations.target_mariadb_version

SELECT VERSION()
=> [["10.11.7-MariaDB-1:10.11.7+maria~ubu2204"]]
