### ISSUE TITLE
Config values in non-Rails apps

### ISSUE THREAD

**Issue by ryannmcq** [ankane/strong_migrations#265]
I see from other issues that some folks are successfully using Strong Migrations in non-Rails Active Record apps (e.g. Sinatra). I'm trying the same, but running into issues where the gem shows errors for old migrations. It seems that `start_after` is not set, I guess because without Rails I'm not able to run `rails generate strong_migrations:install` to create the initializer with either the default or custom config values. Are there any workarounds? Thanks in advance.

**Comment by ankane** [comment]
Hi @ryannmcq, you can set `start_after` and other options manually in any code that runs before migrations ([example](https://github.com/ankane/strong_migrations?tab=readme-ov-file#existing-migrations)).
