### ISSUE TITLE
Setting NOT NULL on an existing column documentation

### ISSUE THREAD

**Issue by headshota** [ankane/strong_migrations#266]
Hi,

In the README seciton about [Setting NOT NULL on an existing column](https://github.com/ankane/strong_migrations?tab=readme-ov-file#setting-not-null-on-an-existing-column) it is recommended to avoid using `change_column_null` and instead first define check constarint with `add_check_constraint` and then in the second migration validate it with `add_check_constraint`. But then it says to use `change_column_null` again which will create the same issue and will not pass the check. Is this a mistake or am I missing something here?

**Comment by ankane** [comment]
Hi @headshota, it's safe if there's a `NOT NULL` constraint on the column.

**Comment by headshota** [comment]
@ankane `change_column_null :users, :some_column, false` this statement in second migration described in the README is still causing migration to be considered dangerous, am I misunderstanding something?

**Comment by ankane** [comment]
You're likely on an EOL Postgres version (< 12) or have `target_version` set to one, in which case it's not safe.
