### ISSUE TITLE
target_postgresql_version not being set correctly

### ISSUE THREAD

**Issue by novacoole** [ankane/strong_migrations#268]
Hi there,

Just wondering how `target_postgresql_version` is initially set? I was getting a version error after upgrading strong_migrations. It was claiming my PSQL version was 10, when it's 16.3.

I got around this by manually setting `StrongMigrations.target_postgresql_version = 16.3` in an intializer but I couldn't see anything in the README suggesting to do this.

**Comment by ankane** [comment]
Hi @novacoole, it sounds like your app has `target_version` set ([docs](https://github.com/ankane/strong_migrations?tab=readme-ov-file#target-version)). Otherwise, it will use the version from the server.
