### ISSUE TITLE
[Idea] Prevent index removal before concurrent index creation completes

### ISSUE THREAD

**Issue by kromiii** [ankane/strong_migrations#269]
# Issue Description

I encountered an incident while executing a migration that removes an existing index and adds a new concurrent index on the same column. The root cause was that the existing index was removed before the new concurrent index was fully created. This led to a flood of queries being executed without an index, causing performance issues.

```
class UpdateIndexOnStocks < ActiveRecord::Migration[6.1]
  disable_ddl_transaction!
  
  def change
    remove_index :stocks, :product_id
    add_index :stocks, :product_id, unique: true,  algorithm: :concurrently
  end
end
```

## Proposed Solution

I suggest implementing a rule or safeguard in strong_migrations to prevent this type of scenario. The rule should:

1. Detect when an index is being removed and a new index is being added concurrently on the same column(s).
2. Enforce that the new index is created before the old index is removed.
3. Possibly suggest or automatically implement a safer migration pattern, such as:
   - Creating the new index
   - Swapping the old index with the new one
   - Removing the old index

## Questions

1. Is this type of safeguard feasible within the scope of strong_migrations?
2. Are there any existing patterns or best practices that strong_migrations recommends for this scenario?
3. Would it be possible to add a warning or error message when detecting this potentially dangerous migration pattern?

Any guidance or discussion on how to address this issue would be greatly appreciated. Thank you for your time and consideration.

**Comment by fatkodima** [comment]
You might find https://github.com/fatkodima/online_migrations#replacing-an-index useful.

**Comment by kromiii** [comment]
Thank you, I didn't know that repository. I will introduce it to my team!
