### ISSUE TITLE
undefined method `quoted_scope' for StrongMigrations::WrappedConnection

### ISSUE THREAD

**Issue by ViktorKopychko** [ankane/strong_migrations#276]
Hi, @ankane

First of all thank you for this really useful gem.

I've encountered an issue when adding a virtual column. 
Could you please take a look at the following?

My migration looks like this:
`add_column :my_table, :active, :boolean, as: "IF(finished_at IS NULL, 1, NULL)", stored: false`

When I run it the following error is printed in schema.rb

> Could not dump table "my_table" because of following NoMethodError 
undefined method `quoted_scope' for #<StrongMigrations::WrappedConnection:

I've discovered that this method is called from [mysql/schema_dumper](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/mysql/schema_dumper.rb#L82) via send

`scope = @connection.send(:quoted_scope, table_name)`

`StrongMigrations::WrappedConnection` uses `delegate_missing_to :@connection` which does not cover private methods so I was able to fix it by adding 
```
def quoted_scope(name = nil, type: nil)
   @connection.send(:quoted_scope, name, type: type)
end
```
to it.

What do you think about this? Should I make a PR?

Thanks!

**Comment by ankane** [comment]
Hi @ViktorKopychko, thanks for investigating and the detailed report! Fixed in the commit above.

**Comment by ViktorKopychko** [comment]
@ankane that was quick, thanks a lot!
