### ISSUE TITLE
[Enquiry] Is the "Adding a column with a default value" rule still valid?

### ISSUE THREAD

**Issue by thedumbtechguy** [ankane/strong_migrations#277]
Thank you for this gem. I've been using it for a long time.
Today, I had to make some changes in another framework and I went researching the addition of a column safely in postgres.

For a long time, I've always assumed this causes a table rewrite. But I found out this doesn't seem to be the case.

The rule says
> Adding a column with a non-null default causes the entire table to be rewritten.
>
> Instead, add the column without a default value, then change the default.

However, I found this [article](https://www.cybertec-postgresql.com/en/postgresql-alter-table-add-column-done-right/) that states:

> We have to address various scenarios here. The simplest one is to add a column without any default values:
> 
> The important point here is: This operation is really fast because all it does is to run some magic on the system catalog. We do need a full table lock BUT it is a really short lock because PostgreSQL does not actually write this column to disk. The system column knows that one more column should be on disk - as nothing is present the engine can safely assume that the value is indeed NULL.
> 
> A similar trick can be applied if we add a constant default value:
>
> Again the operation is really quick and it does NOT affect the amount of storage we need because this additional column does not make it to disk in the first place:

So I checked the [documentation](https://www.postgresql.org/docs/current/sql-altertable.html) and it said similar.

> When a column is added with ADD COLUMN and a non-volatile DEFAULT is specified, the default is evaluated at the time of the statement and the result stored in the table's metadata. That value will be used for the column for all existing rows. If no DEFAULT is specified, NULL is used. In neither case is a rewrite of the table required.
>
> Adding a column with a volatile DEFAULT or changing the type of an existing column will require the entire table and its indexes to be rewritten.

---

At the very least, it seems the implementation might not be full correct. Just curious if this is due to changes in postgres implementations.

I also found this issue related to mariadb/mysql: https://github.com/ankane/strong_migrations/issues/247

**Comment by ankane** [comment]
Hi @thedumbtechguy, if you're seeing that error, it's likely because you're on an older version of Postgres (< 11) or have `target_version` set to one. Here's the [current guidance](https://github.com/ankane/strong_migrations?tab=readme-ov-file#adding-a-column-with-a-volatile-default-value).

**Comment by thedumbtechguy** [comment]
That makes sense @ankane 
Thank you.

I haven't had that error in a while, I just have carried that knowledge along with me for a long time. Glad to know it's no longer an issue.
