### ISSUE TITLE
The suggestion regarding remove_column can be improved 

### ISSUE THREAD

**Issue by zernie** [ankane/strong_migrations#279]
Currently, the remove_column call is prohibited due to potential problems with cached attributes.

This led me to believe that there wouldn’t be any problems if the table had no records, so I disabled the check using safety_assured.

However, issues can occur even in this case—for example, if a migration takes too long to execute, or if during a deployment, migrations after the one that removed a column fail and the DB has already changed even though the app code is still the same, etc...

I think the suggestion can be improved to let people know rest splitting a column removal into multiple deployments is always preferable. 

What do you think?

**Comment by ankane** [comment]
Hi @zernie, I don't think there's a strong reason to split `remove_column` into multiple migrations, but users who prefer this can use a custom check for it.

**Comment by zernie** [comment]
@ankane oh, I'm not suggesting splitting the migrations into multiple parts. Only the migrations.

Let's say you a users.external_id column.

Two migrations are added and are being deployed simultaneously. 

external_id is removed in a migration #1
#2 fails for some reason or is just slow



The app would start firing errors because it still thinks external_id is present even though it isn't anymore.

**Comment by ankane** [comment]
If you follow the existing instructions (set `ignored_columns` and deploy the code), that won't happen.

**Comment by zernie** [comment]
Yep, but as I've explained in the original post, the suggestion can be made more clear
