### ISSUE TITLE
Started receiving `Statement timeout not supported for this database` errors

### ISSUE THREAD

**Issue by turgs** [ankane/strong_migrations#281]
If anyone knows a way to isolate this gem to just instances where `ActiveRecord::Base.connection.instance_values["config"][:adapter]` is one of the _supported_ database providers, I'd curious to look into that.

Background:

As part of using Rails 8 release candidate and testing SQLite for solid_queue, solid_cable, solid_cache, I started receiving errors:

```
Statement timeout not supported for this database
```

Even though I'm only using PostgreSQL as my primary DB, when I have strong_migrations installed it's also running against migrations for solid_queue, solid_cable, solid_cache.

<details>
<summary>:framed_picture:  Here's what my Rails 8 `database.yml` now is looking like:</summary>

![Screenshot from 2024-10-28 10-01-00](https://github.com/user-attachments/assets/1f7683b7-b42c-4fd1-8f1a-f74d65e931d0)
</details>

I note that strong_migrations doesn't support SQLite, so an error _is_ expected.

https://github.com/ankane/strong_migrations/blob/d08cb5e0776c330c7bf0249e3cb152c8cd0ba130/README.md?plain=1#L7

To workaround this for services using SQLite in Rails 8, I thought I could set `StrongMigrations.safe_by_default = true` somewhere, but I can't quite figure out where yet. 

Anyway, I know this error isn't _directly_ a strong_migrations gem issue, but there was no info online about the error I was getting until I went digging through backtraces. So I thought at least creating the issue here would help others narrow down what's going on.

**Comment by ankane** [comment]
Hi @turgs, added a `skip_databases` option in the commit above. #255
