### ISSUE TITLE
`ANALYZE` after creating an index, is it useful? 

### ISSUE THREAD

**Issue by sponomarev** [ankane/strong_migrations#34]
Hi there!

I've noticed that you suggest running `ANALYZE` after creating an index but is it really useful?  Of course, it always makes sense to run `ANALYZE` frequently or tune it to be more efficient which is a separate topic, but how is it connected with the newly created index? I'm afraid that in no way.

What `ANALYZE` do is gathering some statistics about the content of the table column. The Planner uses it to make an assumption about efficiency. Since column content is not affected by any index, in the majority of the cases it doesn't make sense to run `ANALYZE` after index creation. It would be more efficient to run it after some bulk updates/inserts/deletes.

Am I wrong with my thoughts?

**Comment by ankane** [comment]
Hey @sponomarev, we've seen anecdotal evidence that adding an index can throw off a query plan if statistics are not up-to-date. The feature is opt-in, so no need to enable if you haven't seen similar issues.
