### ISSUE TITLE
[Proposal]: Make all reference constraints deferrable 

### ISSUE THREAD

**Issue by volkanunsal** [ankane/strong_migrations#42]
The foreign key constraints often raise issues when moving data, requiring the programmers to remove them to complete the data load tasks. A better approach is to make them deferrable (only in Postgres) and `SET CONSTRAINTS ALL DEFERRED;` in a transaction block before running your data load script. 

The proposed addition would warn the user if the migration includes a non-deferrable foreign_key constraint.

**Comment by ankane** [comment]
Hey @volkanunsal, thanks for the proposal 👍 Can you add an example of a migration that should raise an error, and as well as one that does it properly?

**Comment by volkanunsal** [comment]
I don't quite know to express the correct way of doing it. The way to alter a constraint requires knowing the name of the constraint, but that name is generated by Rails, and not easily accessible to the programmer. Here is an attempt to show what I mean:
wrong

  ```ruby
  class AddReferenceToProject < ActiveRecord::Migration[5.1]
    def change
      add_foreign_key :users, :projects
    end
  end
  ```

right

  ```ruby
  class AddReferenceToProject < ActiveRecord::Migration[5.1]
    def change
      # Naming our own foreign key. Is there a better way?
      add_foreign_key :users, :projects, name: 'foobar'
      execute("ALTER TABLE users ALTER CONSTRAINT foobar DEFERRABLE INITIALLY IMMEDIATE;")
    end
  end
  ```

**Comment by ankane** [comment]
Hey @volkanunsal, thanks for following up. I don't know if this practice is common, so don't think it makes sense to add right now. I'd like to add support for custom rules at some point, which could allow you to create your own warning around this.

**Comment by ankane** [comment]
fwiw, just added a way to [write custom checks](https://github.com/ankane/strong_migrations#custom-checks-master)
