### ISSUE TITLE
Internal use of `execute` preventing `change` autoreversibility

### ISSUE THREAD

**Issue by DylanReile** [ankane/strong_migrations#44]
Hi!

There are paths when the `Migration` module internally uses `connection.execute`. When these paths are hit while rolling back a migration that uses `change`, it causes ActiveRecord to throw `IrreversibleMigration`: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/command_recorder.rb#L88. ActiveRecord is ignorant of strong_migrations and thinks the user is trying to automatically reverse an arbitrary `execute` statement.

The offending lines are: https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations/migration.rb#L84

https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations/migration.rb#L97

 so for now this prevents:
1.  Rolling back `add_index` within `change` if `StrongMigrations.auto_analyze = true` and using Postgresql.
2. Rolling back `add_column` with type JSON within `change` if using Postgresql.

I'm working around these by using explicit `up`/`down` for now, but it's easy to forget and get tripped up.

**Comment by DylanReile** [comment]
```
          This migration uses execute, which is not automatically reversible.
          To make the migration reversible you can either:
          1. Define #up and #down methods in place of the #change method.
          2. Use the #reversible method to define reversible behavior.
```

**Comment by ankane** [comment]
Hey @DylanReile, thanks for reporting 👍 I was able to reproduce and fix the issue with `add_index` and `auto_analyze`, but not sure how to reproduce the `add_column` one. Can you give an example migration that fails to reverse?

**Comment by DylanReile** [comment]
Wow, @ankane, great response time. 

I took another look. `add_column` isn't actually an issue since the only place `postgresql_version` is called is wrapped in a conditional for `unless direction == :down`: https://github.com/ankane/strong_migrations/blob/master/lib/strong_migrations/migration.rb#L17

You'll want to be careful checking the version in future, though.
