### ISSUE TITLE
[Idea] Including dropping an index as a potentially dangerous operation

### ISSUE THREAD

**Issue by jesszwang** [ankane/strong_migrations#49]
Hi! 

Thanks for your work with strong_migrations - it's a great gem and I'm glad this exists!

Proposal: add drop_index to the list of dangerous operations that strong_migrations catches. As you probably know, this is dangerous because it can turn index lookups into table scans if done improperly.

We've definitely incurred downtime as a result of migrations dropping indexes while using strong_migrations, and would LOVE to roll this check into this gem. Thanks for your work! 👍

**Comment by ankane** [comment]
Hey @jesszwang, thanks for the suggestion 👍 I'm hesitant to add this to the list of dangerous operations (same with `drop_table`), as I think it'll be more noisy than helpful. I've tried to keep it to ones that are (subjectively) surprising that they could cause issues, although maybe the same could be said for `rename_table` and `rename_column`. What message would you give if it were to be added?

**Comment by ankane** [comment]
Cleaning up issues (no response)
