### ISSUE TITLE
Stacktrace with remove_column and optional column type

### ISSUE THREAD

**Issue by BestFriendChris** [ankane/strong_migrations#52]
Hi there,

I just added this gem and immediately bumped into an issue. :-)

When using remove_column with the column type (to allow the down migration to recreate the column) such as:

```ruby
def change
  remove_column :table, :column, :integer
end
```

It is failing with a stack trace:

```
NoMethodError: undefined method `each' for :integer:Symbol
.../gems/strong_migrations-0.3.0/lib/strong_migrations/migration.rb:191:in `options_str'
.../gems/strong_migrations-0.3.0/lib/strong_migrations/migration.rb:47:in `method_missing'
.../db/migrate/20181015190940_remove_column_from_table.rb:3:in `change'
...
```

From looking at the code, it appears to assume the third argument will always be an option hash instead of a column type symbol.

**Comment by ankane** [comment]
Hey @BestFriendChris, thanks for the report 👍 Fixed on master.

**Comment by BestFriendChris** [comment]
Great! Thanks!
