### ISSUE TITLE
[Idea] drop_table as a dangerous operation?

### ISSUE THREAD

**Issue by aldesantis** [ankane/strong_migrations#53]
I know this was also mentioned briefly in #49, but I think `drop_table` should be included in the list of dangerous operations. When a `drop_table` call is detected, we could recommend that the user first removes any code that uses the table and then  deploys the migration separately.

I've just been bit by this (I dropped a table that was still used by the rest of the servers and the load balancer kicked them all out) and it would have been really useful to have strong_migrations warn me about it.

**Comment by ankane** [comment]
Hey @aldesantis, thanks for the suggestion, but still have the same thoughts as in #49. `remove_column` is dangerous because even if you don't have app code that depends on it, it'll cause issues. You use custom checks to implement this yourself if desired.

**Comment by aldesantis** [comment]
Okay, got it! We ended up writing a custom check in the meantime anyway, so if this is something you don’t think has a place in the gem we’ll keep using the custom checks. :)
