### ISSUE TITLE
[Idea] Warn on the addition of a validated foreign key

### ISSUE THREAD

**Issue by iamvery** [ankane/strong_migrations#59]
I recently ran into a problem adding a new foreign key constraint at scale. It seems that by default, when adding a foreign key, the entire table is validated for the new constraint which performs some table locking.

From the [PostgreSQL docs](https://www.postgresql.org/docs/9.6/sql-altertable.html)

>If the constraint is marked NOT VALID, the potentially-lengthy initial check to verify that all rows in the table satisfy the constraint is skipped. 

In my particular case, I was adding the foreign key to a new column which would be NULL for all existing records anyway thus not needing the validation at all. Here's the full example that caused me problems:

```ruby
add_column :foos, :bar_id, :integer
add_foreign_key :foos, :bars
```

And here is the preferred way:

```ruby
add_column :foos, :bar_id, :integer
add_foreign_key :foos, :bars, validate: false
```
Note: `validate: false` which results in `NOT VALID` option being added to the produced `ALTER TABLE` statement.

What do you think?

**Comment by ankane** [comment]
Hey @iamvery, thanks for the suggestion. I think this is best as a custom check. I imagine most of the time foreign keys need to be valid.

**Comment by iamvery** [comment]
Thanks for the response @ankane! I'm a little indifferent on this, but I understand your point. I'm indifferent, because I feel like if the purpose of this library is to protect users from themselves it might go so far to recommend against typical cases like this in the name of safety.

>Strong Migrations detects potentially dangerous operations in migrations, prevents them from running by default, and provides instructions on safer ways to do what you want.

Either way, the custom checks are a great feature that we can take advantage of. Thank you!

**Comment by iamvery** [comment]
Thanks for the follow up here! It's going to be a few days before I can dig in, but this sounds great 👍

**Comment by ankane** [comment]
Going to close this out, but feel free to create a PR
