### ISSUE TITLE
Does strong_migrations find issues with migrations containing raw SQL, or does it only work for migrations that utilize ActiveRecord?

### ISSUE THREAD

**Issue by DanielStevenLewis** [ankane/strong_migrations#65]
It's unclear to me from reading the readme whether strong_migrations can find issues in migrations containing raw SQL, or whether it instead only work for migrations that utilize ActiveRecord. Could someone please let me know, and perhaps also clarify this in the documentation?

**Comment by bheemreddy181** [comment]
It only does work on Native rails ActiveRecord and not on raw SQL but it enforces you put the raw SQL in `safety_assured` block. This is from my experience using Strong_migrations. @ankane can give you a better answer though
