### ISSUE TITLE
[QUESTION] : Does Custom Checks don't run for safety assured blocks ?

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/strong_migrations#66]
I am doing a remove column as below 

```
def up
      remove_column :sample, :region_id 
end
```
Strong migrations enforces me to put a safety assured block as below once I do that successfully 

```
Deploy the code, then wrap this step in a safety_assured { ... } block.

class RemoveColumnrulesets < ActiveRecord::Migration[5.1]
  def change
    safety_assured { remove_column :sample, :region_id }
  end
end
```
In the initializer I have a custom check to stop someone from removing the column for the above table it doesn't really stop it the migrations works successfully 

custom check below : 

```
StrongMigrations.add_check do |method, args|
  if method == :remove_column && args[0].to_s == "sample"
  stop! Don't remove columns on sample table 
 end
end
```

**Comment by ankane** [comment]
Hey @bheemreddy181, `safety_assured` skips all checks, including custom ones. It allows developers to run any migration code.

**Comment by bheemreddy181** [comment]
Is this something we want to enable for custom checks ?

**Comment by ankane** [comment]
Hey @bheemreddy181, this problem seems specific to `remove_column` custom checks, so I don't think it makes sense to change the current behavior. We could add an option to `add_check` that specifies if it can be overridden. Something like:

```ruby
StrongMigrations.add_check(overridable: false) do |method, args|
  # code...
end
```

(with ideally a better name)

**Comment by bheemreddy181** [comment]
yes, that makes sense. you want to label this as an enhancement. if you are ok I could give a try but I need some inputs from you for creating a PR. Thanks for your time :-)

**Comment by bheemreddy181** [comment]
@ankane any chance getting on to this?

**Comment by ankane** [comment]
Hey @bheemreddy181, sorry for the delay. After thinking about it more, I don't think it makes sense to add a new concept (non-overridable checks) just for this use case. You're welcome to fork the gem and make this change for your app, but I don't think it's something I want to include in the main project at this point.

**Comment by bheemreddy181** [comment]
@ankane Sure, Can you update the docs for the same.

**Comment by ankane** [comment]
What would you change in the docs?

**Comment by bheemreddy181** [comment]
Adding an exception for remove_column for custom checks?

**Comment by bheemreddy181** [comment]
thanks, @ankane Happy weekend :-)
