### ISSUE TITLE
change_column is overly inclusive

### ISSUE THREAD

**Issue by LizPrescott** [ankane/strong_migrations#70]
The change_column type error raises for any column change, not just the unsafe ones I'm aware of (changing the column type or the name, making a default value, or adding a constraint of some kind). I am in fact removing a constraint from the column (`null: true`). Is this meant to be flagged as unsafe for some reason?

**Comment by ankane** [comment]
Hey @LizPrescott, it's possible it's too inclusive. I'm not sure how the database handles an `ALTER TABLE` statement when there are no changes to be made, but even if the database treats it as a no-op, Strong Migrations would need to confirm the column settings in the migration match the database exactly. I think this logic will be difficult to get right, so it's probably better to be conservative.

For the `null: true` case, you can use `change_column_null` to change the null constraint without an `ALTER TABLE ... TYPE ...` command.
