### ISSUE TITLE
change_column_null (without 4th argument) still locks postgres

### ISSUE THREAD

**Issue by ABewsher** [ankane/strong_migrations#71]
This is related to:
https://github.com/ankane/strong_migrations/issues/63
https://github.com/ankane/strong_migrations/issues/69
 
I've just run the following on a postgres DB with 7M rows.

```
class AddUserVisibleToEvents < ActiveRecord::Migration[5.1]
  def up
    add_column :events, :user_visible, :boolean, null: true
    change_column_default :events, :user_visible, false
  end

  def down
    remove_column :events, :user_visible
  end
end
```

The above was fast. 👍 

Then I ran:

```
class BackfillAddUserVisibleToEvents < ActiveRecord::Migration[5.1]
  disable_ddl_transaction!

  def change
    Event.in_batches.update_all user_visible: true
  end
end
```

As expected, this took several hours, however it didn't stop the production DB running 👍 

Then I ran this:

```
class AddNullFalseToUserVisibleInEvents < ActiveRecord::Migration[5.1]	
  def change	
    change_column_null(:events, :user_visible, false)	
  end	
end
```

... and it locked the DB  👎 

Note that I have not used the 4th argument but it was still "dangerous".

I removed that migration and then ran:

```
class AddIndexToUserVisibleInEvents < ActiveRecord::Migration[5.1]
  disable_ddl_transaction!

  def change
    add_index :events, :user_visible, algorithm: :concurrently
  end
end
```

And it ran for about 15 minutes and did not lock the DB 👍 

So my question...  now that the index is in place, will `change_column_null(:events, :user_visible, false)` be faster now (since there are no NULL values!) or is there some other way I can SET NOT NULL on the column?

If the index will help, can we warn not to run change_column_null until the index is in place?  Alternatively, if there is some SQL that will add NOT NULL without checking all the existing values, could that be suggested if `change_column_null` is used?

Thanks

**Comment by ankane** [comment]
Hey @ABewsher, which version of Postgres are you on?

I imagine adding an index would make it faster, but I'd try it on a staging database first. You could also try the approach [outlined here](https://medium.com/doctolib/adding-a-not-null-constraint-on-pg-faster-with-minimal-locking-38b2c00c4d1c), but I haven't tried it myself, and seems like it carries a small performance penalty (slows future writes by 0.5%-1%).

If the index approach works, I think that's a better recommendation since Rails has built-in support for those commands (don't need to use `execute`) and `schema.rb` can be dumped properly.

**Comment by ankane** [comment]
In general, I'm a fan of having minimal constraints on the database (unique indexes, but no foreign keys or not null), but I understand not everyone takes that view.

**Comment by ABewsher** [comment]
Thanks for your prompt reply @ankane 

pg gem version 1.1.4
Postgres 10.7

For now we're just not bothering with the constraint.  We did test this on staging before deploying to production, but we'll need more record to test it properly it seems.  ;-) 

If we do try again on staging (with 7M new records), I'll let you know if the index helps.

**Comment by ankane** [comment]
Sounds good

**Comment by ABewsher** [comment]
> Then I ran this:
> 
> class AddNullFalseToUserVisibleInEvents < ActiveRecord::Migration[5.1]	
>   def change	
>     change_column_null(:events, :user_visible, false)	
>   end	
> end
> ... and it locked the DB 👎
> 
> Note that I have not used the 4th argument but it was still "dangerous".

Regardless of what I end up doing, this could still do with a warning as even without the 4th argument it still locked things up.
