### ISSUE TITLE
[Idea] Make it easier to disable rules

### ISSUE THREAD

**Issue by MaicolBen** [ankane/strong_migrations#72]
Awesome gem! We would like to ignore one of the rules, but there is no configuration for that. We though in monkeypatching the code, but the hash with warnings or the `method_missing` are huge. We will end up forking the gem, but that isn't ideal. The gem should be better modularized so it's easier to override.

**Comment by blairanderson** [comment]
Can you provide a code sample using the rule you want to disable?

**Comment by MaicolBen** [comment]
We want to disable https://github.com/ankane/strong_migrations#adding-an-index-postgres, as we have transactions in the deploy level, this allows having Continuous Deployment and rollback automatically. Anyway, there could be other cases where someone wants to disable a rule that might not work for some project. 
I don't see any configurations more than the migration number, but I know that requires some work, what I am asking it's to improve the code and that will make easier to override.

**Comment by bheemreddy181** [comment]
maybe a question here, how does having a transaction at deploy level will help for adding_index @MaicolBen ? As your index gets an exclusive lock on the table will have downtime even if you that in a transaction. Maybe I am getting this wrong

**Comment by MaicolBen** [comment]
> As your index gets an exclusive lock on the table will have downtime
In a big table, yes, otherwise it shouldn't take long. 

We are open to other suggestions to do an automated CD, but we mostly don't use concurrent indexes (a wild guess is that 95% of our indexes occur in small tables), if we have to do it, we can do it manually outside the deploy process. Suggesting a concurrent index in most cases will work locally but will fail in production as we have a transaction there. 
Let's say, we can still use the rule, but we want to add more information to the suggestion so the developer can take action, for example if we suggest using `disable_ddl_transaction`, the developer should rescue accordingly so the migration can be rollbacked automatically.

**Comment by bheemreddy181** [comment]
```
Suggesting a concurrent index in most cases will work locally but will fail in production as we have a transaction there
```
I don't think above line is true, because the reason behind adding it concurrently is giving read and write access to the table while adding index so I don't see a reason why this will fail in production.

Using Strong_migrations you can add your custom messages as mentioned here if you want more information to the dev https://github.com/ankane/strong_migrations#custom-messages

**Comment by MaicolBen** [comment]
> I don't think above line is true
It throws a psql error, as it is mentioned in the readme. 

I didn't see the custom message in the readme, thanks! We can close the ticket, but bear it in mind in the future (allowing to disable rules).

**Comment by bheemreddy181** [comment]
I am just trying to understand how concurrent indexes cause downtime in general. I also would love to have override rule in place maybe if someone wants to remove column differently. I think for now if you want to override any existing check they can be put into a safety_assured block if you really want to(Generally not recommended from this gem perspective).

**Comment by MaicolBen** [comment]
Yeah, using `safety_assured` isn't ideal. 

> how concurrent indexes cause downtime in general

I might not be clear, they shouldn't cause downtimes. In our case, the transaction in the deploy process will fail with:
`PG::ActiveSqlTransaction: ERROR:  CREATE INDEX CONCURRENTLY cannot run inside a transaction block`

**Comment by bheemreddy181** [comment]
you have to disable_ddl_transaction when you do concurrent indexes as mentioned here: https://github.com/ankane/strong_migrations#adding-an-index-postgres

**Comment by MaicolBen** [comment]
But as I mentioned, I have a transaction outside the migrate, in the deploy process. That allows us to have multi migrations run (from even differents PRs), and if one of them fail, the deploy will rollback all of them (to avoid inconsistencies).

**Comment by ankane** [comment]
Hey @MaicolBen, added support on master: https://github.com/ankane/strong_migrations#disable-checks-master

**Comment by MaicolBen** [comment]
@ankane thank you!
