### ISSUE TITLE
Default column with not null constraint recommendation is incorrect

### ISSUE THREAD

**Issue by hjhart** [ankane/strong_migrations#73]
With a migration that looks like this: 

```
class AddMetricUnitsToPassengerProfiles < ActiveRecord::Migration[5.1]
  def change
    add_column :passenger_profiles, :metric_units, :boolean, default: true, null: false
  end
end
```

We are getting this suggestion:

```
== 20190507182930 AddMetricUnitsToPassengerProfiles: migrating ================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

=== Dangerous operation detected #strong_migrations ===

Adding a column with a non-null default causes the entire table to be rewritten.
Instead, add the column without a default value, then change the default.

class AddMetricUnitsToPassengerProfiles < ActiveRecord::Migration[5.1]
  def up
    add_column :passenger_profiles, :metric_units, :boolean, null: false
    change_column_default :passenger_profiles, :metric_units, true
  end

  def down
    remove_column :passenger_profiles, :metric_units
  end
end

Then backfill the existing rows in the Rails console or a separate migration with disable_ddl_transaction!.

class BackfillAddMetricUnitsToPassengerProfiles < ActiveRecord::Migration[5.1]
  disable_ddl_transaction!

  def change
    PassengerProfile.in_batches.update_all metric_units: true
  end
end
```

The problem is that the first operation removes the default, but doesn't remove the `null: false` constraint. So the first line: `add_column :passenger_profiles, :metric_units, :boolean, null: false` will explode due to null values in a new column.

Removing that part of the line removes the `null: false` constraint on the column.

I looked at previous issues but didn't find anything. We're running the most recent version of the gem: 0.3.1.

Anyone have any insights into this? I know how to write the migration, but I just want to make the recommendation better for other engineers that stumble into this.

**Comment by ankane** [comment]
@hjhart this should be fixed on master. See #63

**Comment by hjhart** [comment]
That's great! Thank you. Do you plan on releasing another version of the gem to rubygems?

**Comment by ankane** [comment]
Yes
