### ISSUE TITLE
[Idea] Allow setting postgresql_version in config

### ISSUE THREAD

**Issue by viamin** [ankane/strong_migrations#75]
Add a `target_postgresql_version` (or something like that) to StrongMigrations config. 
i.e. `StrongMigrations.target_postgres_version = 10.7` which is checked in postgresql_version https://github.com/ankane/strong_migrations/blob/981d4f02e4c758238adf26451b9927270667344c/lib/strong_migrations/checker.rb#L194

Background: 
Adding a column with a default is unsafe in PostgreSQL < 11, and will raise an error. This passed on my local machine because I'm running PostgreSQL v11.3. However, on our staging/production servers, we're running PostgreSQL 10.7. So strong_migrations let the migration through in development, but failed when building on staging. 

It would be safer to allow setting a production target version in StrongMigrations config so this doesn't slip through in development.

**Comment by ankane** [comment]
Hey @viamin, sounds good to me if you want to submit a PR. I think it should only trust the target version in development and test environments. Rails 6 will introduce multiple databases (which could have different versions), but don't think we have to handle that case right now (unless you have ideas).

**Comment by ankane** [comment]
Added in #76
