### ISSUE TITLE
What is an extremely large table?

### ISSUE THREAD

**Issue by jjb** [ankane/strong_migrations#79]
Thanks for an amazing project! There is this message:

> Adding an index with more than three columns only helps on extremely large tables

How large is extremely large? 1G? 1TB?

Have any reading I can do on this? I can then do a PR adding some info to this message and to the readme.

Thanks!
John

**Comment by ankane** [comment]
It really depends on how well the indexes columns narrow down the results, but from my experience, you pretty much never need this (and will know if you do). Not exactly sure the best way to get that across in the readme.

**Comment by jjb** [comment]
Gotcha. Have you ever decided to use 4 columns?

**Comment by ankane** [comment]
Not that I can recall.
