### ISSUE TITLE
[Idea] Also lint Procfile for "release: rake db:migrate"

### ISSUE THREAD

**Issue by ohaddahan** [ankane/strong_migrations#81]
Although the `Procfile` isn't a migration per-say, adding` release: rake db:migrate `to it is recommended and is related to proper migrations.

**Comment by ankane** [comment]
Hey @ohaddahan, thanks for this idea as well. It makes sense for some teams running on Heroku, but I think a team choosing to run migrations manually is fine as well, so I wouldn't want to include a check for it.
