### ISSUE TITLE
[QUESTION] : Can we do the validate foreign key in the same migration where we add it 

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/strong_migrations#84]
Can we have the validate foreign key validation in the same migration for addition

like

```
class AddForeignKeyOnUsers < ActiveRecord::Migration[5.2]
  def change
    add_foreign_key :users, :orders, validate: false
    validate_foreign_key :users, :orders
  end
end
```

do these should be in separate migrations so that they happen on a separate transaction

**Comment by ankane** [comment]
They should be in separate migrations so they happen in separate transactions.

**Comment by MaicolBen** [comment]
Is this for existing fields? I don't see it will lock the table if the field is new
