### ISSUE TITLE
Fresh install, no warning

### ISSUE THREAD

**Issue by Meekohi** [ankane/strong_migrations#89]
Apologies I must be missing something obvious... installed the gem, created this migration:
```
class AddBadStuff < ActiveRecord::Migration[5.2]
  def change
    add_column :events, :dumb_text, :text, default: "lame"
  end
end
```
and ran `rake db:migrate`... no warning. Is this not how the gem is intended to be used? Additional installation instructions?

Rails 5.2.2.1
Postgres 9.x

**Comment by Meekohi** [comment]
Postgres version in development was 11.x 🤕

**Comment by ujh** [comment]
What was the solution here @Meekohi? I just ran into this myself where `rake db:migrate` worked during development but then failed when running on production.

**Comment by Meekohi** [comment]
The issue where `add_column` with a default would lock the tables was resolved in Postgres 11.x -- so if you're on a new version this gem will correctly not report an issue.
