### ISSUE TITLE
change_column_null without default is advocated as safe, while it is not

### ISSUE THREAD

**Issue by bezmax** [ankane/strong_migrations#90]
Hello,

In code and even documentation `change_column_null` without a default value is advocated as being a "safe" operation. In reality for large datasets it is not safe, at least not in any version of Postgres. 

To execute `ALTER COLUMN SET NOT NULL`, Postgres needs to do a full sequential scan of every record in table to validate that there are no records violating the new constraint. This is being done within the atomic `ALTER COLUMN` operation, which acquires an access exclusive lock to the whole table. Meaning that nothing can touch the table while it's being scanned. 

The correct, truly "safe" way to add a NOT NULL constraint in Postgres, is:
```
-- This requires access exclusive lock, but NOT VALID part makes it instantaneous
ALTER TABLE tbl ADD CONSTRAINT col_not_null CHECK (col IS NOT NULL) NOT VALID;

-- This actually validates the new constraint in a separate step, which only needs a very permissive SHARE UPDATE EXCLUSIVE lock
ALTER TABLE tbl VALIDATE CONSTRAINT col_not_null;
```

Sadly, Postgres does not provide any safe ways to validate the "real" `NOT NULL` constraint.

**Comment by ankane** [comment]
Hey @bezmax, thanks for the reporting. This seems to be consistent with #71 and [this post](https://medium.com/doctolib/adding-a-not-null-constraint-on-pg-faster-with-minimal-locking-38b2c00c4d1c).

I think we can raise an error for `change_column_null :table, :column, false`. Unfortunately, apps will need to switch to `structure.sql` for constraints to be saved, and it looks like there's a small performance hit of 0.5-1% from the post above.

Have you tried it when there's an index on the column? I imagine it significantly reduces the lock time.

**Comment by ankane** [comment]
Just ran some tests so see if an index speeds it up. Unfortunately, it doesn't. A `CHECK (col IS NOT NULL)` does starting in Postgres 12 ([discussion](https://www.postgresql.org/message-id/flat/81911511895540%40web58j.yandex.ru)), which makes it easy to transition from a constraint to a `NOT NULL` column.

There's [a gem](https://github.com/nullobject/rein) that allows you to add constraints and keep `schema.rb`, but it doesn't support the `NOT VALID` option yet: https://github.com/nullobject/rein/issues/47

My current thinking is to raise a warning with `change_column_null` and suggest the approach in the first comment via `execute`. If `NOT VALID` support is added to Rein, Strong Migrations can automatically detect the gem and suggest `add_null_constraint` instead.

**Comment by joehorsnell** [comment]
Ping @ankane - FYI I’ve opened a PR with Rein to add support for [NOT VALID constraints](https://github.com/nullobject/rein/pull/52)

**Comment by ankane** [comment]
@joehorsnell Awesome, that'll make this pattern much cleaner for users.
