### ISSUE TITLE
README backfilling example is missing `safety_assured`

### ISSUE THREAD

**Issue by machty** [ankane/strong_migrations#91]
https://github.com/ankane/strong_migrations/blob/master/README.md#backfilling-data

If you follow the Good example of backfilling data, you'll get

`ZeroDowntimeMigrations::UnsafeMigrationError: Disabling the DDL transaction is unsafe!`

The example should have `safety_assured`; I'd put in a PR for it, but seems weird? Is this an issue with the README or perhaps a bug that can be fixed?

**Comment by ankane** [comment]
Hey @machty, it looks like you have the zero_downtime_migrations installed instead of Strong Migrations.

**Comment by machty** [comment]
Oops! sorry, was following links from a coworker :)
