### ISSUE TITLE
Can we add documentation 

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/strong_migrations#96]
Ankane, 

Can we add more documentation for each release like a release notes saying what all features or bug fixes for improvements we are doing?

**Comment by ankane** [comment]
Hey @bheemreddy181, the changelog should have that info.

**Comment by bheemreddy181** [comment]
I mean something more like this , if it makes sense :-)
<img width="757" alt="Screen Shot 2019-11-18 at 6 31 18 PM" src="https://user-images.githubusercontent.com/3464623/69105689-aa983b00-0a31-11ea-8257-4f0a8e754e06.png">

**Comment by ankane** [comment]
Can you explain more? Not sure I understand the suggestion.

**Comment by bheemreddy181** [comment]
Sorry i missed the https://github.com/ankane/strong_migrations/blob/master/CHANGELOG.md file for some reason , this isn’t a conern :-)
