### ISSUE TITLE
Removing Index isn't a safe operation in Postgres.

### ISSUE THREAD

**Issue by NavindrenBaskaran** [ankane/strong_migrations#98]
Strong Migration considers removing index non-concurrently as a safe operation in contrast to what's stated in the postgres [documentation](https://www.postgresql.org/docs/11/sql-dropindex.html). DROP INDEX command will acquire an exclusive lock block inserts, updates and deletes on that locked table. If we agree, i will be make the necessary changes for this.

**Comment by ankane** [comment]
Hey @NavindrenBaskaran, thanks for the suggestion. I've actually been considering this in #95 as an optional check and had it mostly written. This operation does lock the table, but like `add_column`, the lock is very brief, so I don't think it should be enabled by default (from personal experience, I haven't had issues with this on very large, active databases, but can see how it's possible with different workloads).
