### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/strong_migrations#99]
How about below features 

1. Timeouts on the migrations rather than using [this gem ](https://github.com/gocardless/activerecord-safer_migrations)
2. adding a feature to Retry migrations if fails because of timeouts 
3. Ignoring timeouts for concurrent indexes

**Comment by ankane** [comment]
Hey @bheemreddy181, thanks for the suggestions. Can you give more details about how your timeouts are configured and how each of these are currently affecting your app?

**Comment by bheemreddy181** [comment]
Recently there was a long running query which replicated the data from master dB to some where else which is bad ( in terms of performance) but this query was blocking the migration which adding new column which is trying to acquire Access Exclusive  Lock Which in-turn was blocking all application functional queries behind which typically caused a downtime for the APP. We never had timeouts set on the user level as it has to be configured it has to be set at each environment level. This is a rough example.

**Comment by ankane** [comment]
Thanks. I'm hesitant to add features around timeouts because I think the best approach for most apps is to use a separate database user that has a short lock timeout (5s-10s) and a long statement timeout, and all of this can be configured at the database level in many cases.

**Comment by bheemreddy181** [comment]
I was more looking into one strong migrations which does everything in terms of migrations helper and all the above can be optional features rather than enforcing. Again retry mechanism based on the timeout failure will really help as well for everyone. May be in future we can check pg_stat_activity if there are any long running queries. Let me know your thoughts ?

**Comment by ankane** [comment]
I think what I'm trying to say is I don't think it should be needed. If you set a short lock timeout and a long statement timeout for the user running migrations:

1. You don't need to worry about changing timeouts for specific migrations 
2. No migrations should fail due to statement timeouts
3. Migrations may fail on lock timeouts but will fail quickly, avoiding the downtime issue described above. If a migration fails due to a lock timeout, you can just rerun it again.

**Comment by ankane** [comment]
It could be useful to have something like:

```ruby
StrongMigrations.lock_timeout = 5.seconds
StrongMigrations.statement_timeout = 1.hour
```

so users can set these without using a different database user (this approach fails with PgBouncer, but can have a note about that).

**Comment by bheemreddy181** [comment]
I would like to get your thoughts around if we can re-run the migration with strong_migrations in production if migration failed because of the timeout set?

**Comment by ankane** [comment]
This situation should be rare in practice if you take the approach above, so I don't think it makes sense to add.

**Comment by ankane** [comment]
Added statement and lock timeouts for Postgres.
